package bansy21.Gui;

import bansy21.Red.*;
import javax.swing.*;
import java.lang.*;

import java.awt.*;
import java.io.*;
// -------------------------------------------------------------------------------------
/*
 * RepRedG.java
 * @author  Arturo Alatriste Trujillo.
 * Reporte de Red: Muestra los datos de todos los nodos.
 */
// -------------------------------------------------------------------------------------
public class RepRedG extends javax.swing.JInternalFrame {
    
    /** Creates new form RepRedG */
    public RepRedG( Red pred ) {
        initComponents();
        red = pred;
        pack(); show();
//        Reporte();
        Reporte2();
        pack(); show();
    }

    public RepRedG( Red pred, int TipoRep ) {
        initComponents(); red = pred;
        if ( TipoRep == 1 ) Reporte();
        else                Reporte2();
    }
// -------------------------------------------------------------------------------------
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
//        setTitle("Reporte de Red (Gr\u00e1fico)");
        setVisible( true );

        BtnGuardarComo = new javax.swing.JButton();
        BtnGuardarComo.setText("Guardar como ...");

        BtnGuardarComo.addActionListener(new java.awt.event.ActionListener() 
        {  public void actionPerformed(java.awt.event.ActionEvent evt) 
           { BtnGuardarComoActionPerformed(evt); }
	  });

        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser1.setToolTipText("null");
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() 
        {  public void actionPerformed(java.awt.event.ActionEvent evt) 
           { jFileChooser1ActionPerformed(evt); }
        });

        BtnGuardarComo.setText("Guardar como CSV...");
        getContentPane().add(BtnGuardarComo, java.awt.BorderLayout.NORTH);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AnchoRep = 400;
        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(AnchoRep, 10));
        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);
        pack();
        RenglonEspacio = 20; Renglon = 20; Y = 50; 
        texto = new String("Reporte de Red."); texto += "\n \n";

    }//GEN-END:initComponents
// -------------------------------------------------------------------------------------
    private void BtnGuardarComoActionPerformed(java.awt.event.ActionEvent evt) 
    { int x;
      x = jFileChooser1.showSaveDialog(this);
    }
// -------------------------------------------------------------------------------------
    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) 
    { File fichSalida = new File("C:\\" );
      try{ //Guarda un texto en un archivo
      //Se recupera el texto del campo y se convierte en un array

      // texto es String
      byte b[] = texto.getBytes();
        
      //Se asigna nombre al archivo
      fichSalida = jFileChooser1.getSelectedFile();  
        
      //Se crea el canal de salida conectado a este archivo
      FileOutputStream canalSalida = new FileOutputStream( fichSalida );
      //Se escribe el contenido del array de bytes en el archivo
      canalSalida.write( b );
      //Se cierra el canal
      canalSalida.close();
      }catch( IOException e){ e.printStackTrace(); }
    }
// -------------------------------------------------------------------------------------
// Genera reporte
    public void Reporte() {
      this.setTitle("Reporte de Red (Tipo 1)");

	Node n = red.inicio;
      JTable t;
	while ( n != null )
	{
		AgregaNodoNombre( n.name  );
            texto += "NODO: " + n.name + "\n\n";   
            t = LeeTablaProb( n ); AgregaTabla( t, 80 ); 
            texto += TablaString( t ) + "\n";   

            t = LeeTablaPadres( n ); 
            if ( t != null )
            {
              AgregaTabla( t, 80 ); 
              texto += TablaString( t ) + "\n";   
            }

            texto += "------------------------------------------------ \n\n";   
		n = n.sig;
	}
    }
// -------------------------------------------------------------------------------------
    public void Reporte2() {
      this.setTitle("Reporte de Red (Tipo 2)");
	Node n = red.inicio;
      JTable t1, t2;
      int k;
	while ( n != null )
	{
		AgregaNodoNombre( n.name  );
            texto += "NODO: " + n.name + "\n\n";   
            k = Y;
            t1 = LeeTablaProb( n ); AgregaTabla( t1, 20 ); 

            t2 = LeeTablaPadres( n ); 
            if ( t2 != null )
            {
              Y = k;
              AgregaTabla( t2, AnchoTablaProb + 20 ); 
            }
            texto += TablaString( t1, t2 );

            texto += "------------------------------------------------ \n\n";   
		n = n.sig;
	}
    }
// -------------------------------------------------------------------------------------
// Agrega el Nombre del nodo
    public void AgregaNodoNombre( String Nombre ) {
        javax.swing.JLabel jLabelx = new javax.swing.JLabel();
        jLabelx.setText( Nombre );
        jLabelx.setVisible( true );
        jPanel1.add(jLabelx, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, Y, -1, -1));
        jPanel1.setPreferredSize(new java.awt.Dimension(680, Y + 2*RenglonEspacio));
        jScrollPane1.setViewportView(jPanel1);        
        pack(); show(); 

//        Y += jLabelx.getHeight() + RenglonEspacio;
        Y += Renglon + RenglonEspacio;

        jPanel1.setPreferredSize(new java.awt.Dimension(AnchoRep, Y + 2*RenglonEspacio));
        jScrollPane1.setViewportView(jPanel1);        
        pack();
    }
// -------------------------------------------------------------------------------------
// Agrega tabla 
    public void AgregaTabla( JTable Tabla, int X ) {
        int alto, ancho;
        Tabla.setColumnSelectionAllowed( false );
        JScrollPane PanelTabla = new JScrollPane( Tabla );
        jPanel1.add( PanelTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(X, Y, -1, -1));        
        jScrollPane1.setViewportView(jPanel1);    
        pack(); show();
        alto  = Tabla.getRowCount() * Tabla.getRowHeight();
        ancho = Tabla.getColumnCount() * 150;
        AnchoTablaProb = ancho;
        if ( X + ancho > AnchoRep )AnchoRep = X + ancho + 20;
        Y += alto + 2*RenglonEspacio;        
        PanelTabla.setPreferredSize(new java.awt.Dimension(ancho, alto + RenglonEspacio + 4));
        jPanel1.setPreferredSize(new java.awt.Dimension( AnchoRep + ancho, Y + 2*RenglonEspacio));
        jScrollPane1.setViewportView(jPanel1);    
        pack();        
    }
// -------------------------------------------------------------------------------------
// Devuelve los nombre de las columnas d una tabla.
    public String NomColString( JTable t ) {
        String s = new String("");
        for( int c = 0; c < t.getColumnCount(); c++ )
        {
          if ( c < t.getColumnCount() - 1 )
               s += t.getColumnName(c) + ", ";
          else s += t.getColumnName(c);
        }
        return( s );
    }
// -------------------------------------------------------------------------------------
// Devuelve un String a partir de una tabla.
    public String TablaString( JTable t ) {
        String s = new String("");
        s = NomColString( t ) + "\n"; 

/*
        for( int c = 0; c < t.getColumnCount(); c++ )
        {
          if ( c < t.getColumnCount() - 1 )
               s += t.getColumnName(c) + ", ";
          else s += t.getColumnName(c) + "\n";
        }
*/

        for( int r = 0; r < t.getRowCount(); r++ )
        {
          for( int c = 0; c < t.getColumnCount(); c++ )
          {
            if ( c < t.getColumnCount() - 1 )
                 s += t.getValueAt(r, c) + ", ";
            else s += t.getValueAt(r, c) + "\n";
          } 
        }
        return( s );
    }
// -------------------------------------------------------------------------------------
    public String TablaString( JTable t1, JTable t2 ) {
        int r, c;
        String s = new String("");
        s = NomColString( t1 ); 
        if ( t2 != null) 
             s += ", " + NomColString( t2 ) + "\n"; 
        else s += "\n"; 

        for( r = 0; r < t1.getRowCount(); r++ )
        {
          for( c = 0; c < t1.getColumnCount(); c++ )
          {
            if ( c < t1.getColumnCount() - 1 )
                 s += t1.getValueAt(r, c) + ", ";
            else s += t1.getValueAt(r, c);
          } 
          if ( t2 != null)
          {
            s += ", "; 
            for( c = 0; c < t2.getColumnCount(); c++ )
              if ( c < t2.getColumnCount() - 1 )
                   s += t2.getValueAt(r, c) + ", ";
              else s += t2.getValueAt(r, c) + "\n";
          }
          else s += "\n";
        }
        return( s );
    }
// -------------------------------------------------------------------------------------
// Obtiene la tabla de Probabilidades del nodo
    public JTable LeeTablaProb( Node nodo ) {
        JTable Tabla;
        //tabla de probabilidades
        Object[] columns = new Object[nodo.values.size()];
        nodo.values.copyInto(columns);

        // Crea tabla con:  un arreglo de Datos,  y Nombre de las columnas
        Tabla = new JTable( (Object[][])nodo.table, columns );
        Tabla.setToolTipText("Tabla de Probabilidades Condicionales.");
        return( Tabla );
    }
// -------------------------------------------------------------------------------------
// Obtiene la tabla de datos de los padres
    public JTable LeeTablaPadres( Node nodo ) {
        JTable Tabla = null;
        Object[] columns = new Object[nodo.parents.size()];
        for ( int i = 0; i < nodo.parents.size(); i++ )
        { columns[i] = ( (Node)nodo.parents.elementAt(i) ).name; }

        if ( nodo.parents.size() > 0 ) 
        { Tabla = new JTable((Object[][])nodo.parentComb, columns); }
        return( Tabla );
    }
// -------------------------------------------------------------------------------------
    public  int Y;    
    public  int Renglon;        
    public  int RenglonEspacio;        
    public  int AnchoTablaProb;
    public  int AnchoRep;
    private String texto;
    public  Red red;    
    public  JScrollPane jScrollPane1;
    public  JButton BtnGuardarComo;
    public  JPanel jPanel1;
    private JFileChooser jFileChooser1;
}
// -------------------------------------------------------------------------------------
// Fin.
// -------------------------------------------------------------------------------------
