package bansy21.Gui;
//package org.netbeans.lib.awtextra;

import bansy21.frmPrincipal;
import javax.swing.*;
import java.awt.*;
import java.util.*;
import java.text.*;
import java.lang.*;
import org.netbeans.lib.awtextra.*;

/*
 * VenParametros.java
 *
 * Created on 25 de septiembre de 2004, 11:52 AM
 */

/**
 *
 * @author  Arturo Alatriste Trujillo.
 */
// -----------------------------------------------------------------------------
// public class VenParametros extends javax.swing.JFrame {
  public class VenParametros extends javax.swing.JInternalFrame {
//  public class VenParametros extends javax.swing.JDialog {
 
    /** CONSTRUCTORES - Creates new form VenParametros */
//    public VenParametros() { initComponents(); show(); }

    public VenParametros( frmPrincipal LH ) {
//	  super( LH, "Parametros", true );
        hta = LH;
        initComponents(); 
        LeeDatos();  
        pack();
        show(); 
    }

// -----------------------------------------------------------------------------    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_Decimales = new javax.swing.JTextField();
        jTextField_Variables = new javax.swing.JTextField();
        jTextField_Casos = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_AlfaG       = new javax.swing.JTextField();
        jTextField_Profundidad = new javax.swing.JTextField();
        jTextField_GIM         = new javax.swing.JTextField();
        Btn_Aceptar = new javax.swing.JButton();
        Btn_Cancelar = new javax.swing.JButton();

//        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().setLayout(new AbsoluteLayout());

        setClosable(true);
        setIconifiable(true);
        setMaximizable(false);
        setPreferredSize( new Dimension(530, 230) );
        setTitle("Parametros");
        setResizable(false);
	  setSize(520, 230);
        setVisible(true);

/*        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
*/

//        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.setLayout(new AbsoluteLayout());


        jPanel1.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(), "Generales"));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("N\u00famero de variables");
//        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 130, -1));
        jPanel1.add(jLabel1, new AbsoluteConstraints(10, 30, 130, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("N\u00famero de casos");
//        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 130, -1));
        jPanel1.add(jLabel2, new AbsoluteConstraints(10, 70, 130, -1));


        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("N\u00famero de decimales");
//        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 130, -1));
        jPanel1.add(jLabel3, new AbsoluteConstraints(10, 110, 130, -1));


        jTextField_Decimales.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_Decimales.setText("4");
//        jPanel1.add(jTextField_Decimales, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 70, -1));
        jPanel1.add(jTextField_Decimales, new AbsoluteConstraints(150, 110, 70, -1));

        jTextField_Variables.setEditable(false);
        jTextField_Variables.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_Variables.setText("0");
//        jPanel1.add(jTextField_Variables, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 70, -1));
        jPanel1.add(jTextField_Variables, new AbsoluteConstraints(150, 30, 70, -1));


        jTextField_Casos.setEditable(false);
        jTextField_Casos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_Casos.setText("0");
//        jPanel1.add(jTextField_Casos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 70, -1));
        jPanel1.add(jTextField_Casos, new AbsoluteConstraints(150, 70, 70, -1));


//        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 150));
        getContentPane().add(jPanel1, new AbsoluteConstraints(10, 10, 240, 150));

//        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.setLayout(new AbsoluteLayout());

        jPanel2.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(), "De aprendizaje"));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Alfa global (%)");
//        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, -1));
        jPanel2.add(jLabel4, new AbsoluteConstraints(20, 30, 140, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Profundidad");
//        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 140, -1));
        jPanel2.add(jLabel5, new AbsoluteConstraints(20, 70, 140, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("% Ganancia de Inf m\u00ednima");
        jLabel6.setToolTipText("Porcentage de Ganancia de Informaci\u00f3n M\u00ednima");
//        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        jPanel2.add(jLabel6, new AbsoluteConstraints(20, 110, -1, -1));

        jTextField_AlfaG.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_AlfaG.setText("1");
//        jPanel2.add(jTextField_AlfaG, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 60, -1));
        jPanel2.add(jTextField_AlfaG, new AbsoluteConstraints(170, 30, 60, -1));

        jTextField_Profundidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_Profundidad.setText("1");
//        jPanel2.add(jTextField_Profundidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 60, -1));
        jPanel2.add(jTextField_Profundidad, new AbsoluteConstraints(170, 70, 60, -1));

        jTextField_GIM.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_GIM.setText("1");
//        jPanel2.add(jTextField_GIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 60, -1));
        jPanel2.add(jTextField_GIM, new AbsoluteConstraints(170, 110, 60, -1));

//        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 250, 150));
        getContentPane().add(jPanel2, new AbsoluteConstraints(260, 10, 250, 150));

        Btn_Aceptar.setText("Aceptar");
        Btn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AceptarActionPerformed(evt);
            }
        });

//        getContentPane().add(Btn_Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));
        getContentPane().add(Btn_Aceptar, new AbsoluteConstraints(160, 170, -1, -1));

        Btn_Cancelar.setText("Cancelar");
        Btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CancelarActionPerformed(evt);
            }
        });
//        getContentPane().add(Btn_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));
        getContentPane().add(Btn_Cancelar, new AbsoluteConstraints(270, 170, -1, -1));


/*	Rectangle screenRect = this.getGraphicsConfiguration().getBounds();
	this.setLocation(		screenRect.x + screenRect.width/2 - this.getSize().width/2,
		screenRect.y + screenRect.height/2 - this.getSize().height/2);	 
*/

        pack();
    }//GEN-END:initComponents
// -----------------------------------------------------------------------------
    private void LeeDatos() {
      DecimalFormat df = new DecimalFormat( "#" );
      Variables = new Integer( hta.bPE.numVariables );
      Casos     = new Integer( hta.bPE.Casos        );
      Decimales = new Integer( hta.bPE.Decimales    );

      AlfaG       = new Double(  hta.bPE.alfaG * 100 ); 
      Profundidad = new Integer( hta.bPE.profundidad );
      GIM         = new Double(  hta.bPE.minPorcGan  );  //Ganancia de Informacion Mínima

      jTextField_Variables.setText( Variables.toString() ); 
      jTextField_Casos.setText(     Casos.toString()     ); 
      jTextField_Decimales.setText( Decimales.toString() ); 

      jTextField_AlfaG.setText( df.format( AlfaG.doubleValue() ) ); 
      jTextField_Profundidad.setText( Profundidad.toString()     );
      jTextField_GIM.setText(   df.format( GIM.doubleValue()   ) );
   }
// -----------------------------------------------------------------------------    
    private void Btn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {
      AlfaG       = new Double(  jTextField_AlfaG.getText()       );
      Profundidad = new Integer( jTextField_Profundidad.getText() );
      GIM         = new Double(  jTextField_GIM.getText()         );  //Ganancia de Informacion Mínima
      Decimales   = new Integer( jTextField_Decimales.getText()   );

      hta.bPE.alfaG       = AlfaG.doubleValue() / 100;
      hta.bPE.profundidad = Profundidad.intValue();
      hta.bPE.minPorcGan  = GIM.doubleValue();
      hta.bPE.Decimales   = Decimales.intValue();

      hta.bPE.PatronDecimales = "#0.";
      for( int k = 1; k <= hta.bPE.Decimales; k++) hta.bPE.PatronDecimales += "0";

      try{   this.setClosed(true); } catch( Exception e) {} //Cierra ventana
    }
// -----------------------------------------------------------------------------
    private void Btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CancelarActionPerformed
        try{   this.setClosed(true); } catch( Exception e) {}
    }//GEN-LAST:event_Btn_CancelarActionPerformed
// -----------------------------------------------------------------------------    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
// -----------------------------------------------------------------------------    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        new VenParametros().show();
    }
    


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField_Variables;
    private javax.swing.JTextField jTextField_Casos;
    private javax.swing.JTextField jTextField_Decimales;

    private javax.swing.JTextField jTextField_AlfaG;
    private javax.swing.JTextField jTextField_Profundidad;
    private javax.swing.JTextField jTextField_GIM; //Ganancia de Informacion Mínima

    public frmPrincipal hta;
    public Integer Variables;
    public Integer Casos;
    public Integer Decimales;
    public Double  AlfaG;
    public Integer Profundidad;
    public Double  GIM; //Ganancia de Informacion Mínima

    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton Btn_Aceptar;
    private javax.swing.JButton Btn_Cancelar;
    // End of variables declaration//GEN-END:variables
}
// -----------------------------------------------------------------------------