/*
 * nodePrope.java
 *
 * Created on 19 de diciembre de 2006, 03:09 PM
 */

package bansy21.Gui;
import bansy21.frmPrincipal;
import bansy21.Red.*;

/**
 *
 * @author  Humberto
 */
public class nodePrope extends javax.swing.JFrame {
    
    private Node node;
    public boolean cancel=true;
    public boolean noBayesN=true;
        
    /** Creates new form nodePrope */
    public nodePrope() {
        initComponents();
    }
    
    public nodePrope(frmPrincipal padre, Node no)
	{
         initComponents();
         node=no;
         agregarValoresCombos();
         
    }
    
    private void populateTable()
    {
        Object[] columns = new Object[node.values.size()];
	node.values.copyInto(columns);
        table.removeColumnSelectionInterval(0, table.getColumnCount()-1);
        table.addColumnSelectionInterval(0, columns.length);
    }
    
    private void agregarValoresCombos()
    {
        int count=node.values.size();
        for(int i=0;i<count;i++)        
            values.addItem(node.values.elementAt(i));
        for(int i=0;i<count;i++)
            tipoNodo.addItem(TipoNodo.tiposNodo[i]);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        values = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        tipoNodo = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setText("Valor Seleccionado");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel2.add(values, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 200, -1));

        jLabel2.setText("Tipo de Nodo");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jPanel2.add(tipoNodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 200, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 380, 90));

        jScrollPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 100));

        jButton1.setText("OK");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        jButton2.setText("Cancelar");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        pack();
    }
    // </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nodePrope().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable table;
    private javax.swing.JComboBox tipoNodo;
    private javax.swing.JComboBox values;
    // End of variables declaration//GEN-END:variables
    
}
