package bansy21.Gui;
//package org.netbeans.lib.awtextra;

import bansy21.frmPrincipal;
import javax.swing.*;
import java.awt.*;
import java.util.*;
import java.text.*;
import java.lang.*;
import org.netbeans.lib.awtextra.*;
 

/*
 * VdParametros.java
 *
 * Created on 27 de septiembre de 2004, 10:13 PM
 */

/**
 *
 * @author  Arturo Alatriste Trujillo.
 */
// -----------------------------------------------------------------------------

public class VdParametros extends javax.swing.JDialog {
    
    /** Constructores */
/*    public VdParametros(java.awt.Frame parent, boolean modal) {
        super(parent, modal); initComponents(); } */

    public VdParametros(frmPrincipal LH) {
        super(LH, true);
        hta = LH;
        initComponents();
        LeeDatos();  
    }
// -----------------------------------------------------------------------------
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

         //----------------- Crea instancias

        jPanel1 = new javax.swing.JPanel();
        jLabel_Variables = new javax.swing.JLabel();
        jLabel_Casos     = new javax.swing.JLabel();
        jLabel_Decimales = new javax.swing.JLabel();

        jTextField_Variables = new javax.swing.JTextField();
        jTextField_Casos     = new javax.swing.JTextField();
        jTextField_Decimales = new javax.swing.JTextField();

        jPanel2 = new javax.swing.JPanel();
        jLabel_AlfaG       = new javax.swing.JLabel();
        jLabel_Profundidad = new javax.swing.JLabel();
        jLabel_GIM         = new javax.swing.JLabel();

        jTextField_AlfaG       = new javax.swing.JTextField();
        jTextField_Profundidad = new javax.swing.JTextField();
        jTextField_GIM         = new javax.swing.JTextField();

        Btn_Aceptar = new javax.swing.JButton();
        Btn_Cancelar = new javax.swing.JButton();

        //----------------- PANEL PRINCIPAL

        getContentPane().setLayout(new AbsoluteLayout());

        setTitle("Parametros");
        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        //----------------- PANEL 1
        jPanel1.setLayout(new AbsoluteLayout());
        jPanel1.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(), "Generales"));

        jLabel_Variables.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Variables.setText("N\u00famero de variables");
        jPanel1.add(jLabel_Variables, new AbsoluteConstraints(10, 30, 130, -1));
        jPanel1.add(jLabel_Variables, new AbsoluteConstraints(10, 30, 130, -1));

        jLabel_Casos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Casos.setText("N\u00famero de casos");
        jPanel1.add(jLabel_Casos, new AbsoluteConstraints(10, 70, 130, -1));

        jLabel_Decimales.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Decimales.setText("N\u00famero de decimales");
        jPanel1.add(jLabel_Decimales, new AbsoluteConstraints(10, 110, 130, -1));

        jTextField_Variables.setEditable(false);
        jTextField_Variables.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_Variables.setText("0");
        jPanel1.add(jTextField_Variables, new AbsoluteConstraints(150, 30, 70, -1));

        jTextField_Casos.setEditable(false);
        jTextField_Casos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_Casos.setText("0");
        jPanel1.add(jTextField_Casos, new AbsoluteConstraints(150, 70, 70, -1));

        jTextField_Decimales.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_Decimales.setText("4");
        jPanel1.add(jTextField_Decimales, new AbsoluteConstraints(150, 110, 70, -1));

        getContentPane().add(jPanel1, new AbsoluteConstraints(10, 10, 240, 150));


        //----------------- PANEL 2

        jPanel2.setLayout(new AbsoluteLayout());
        jPanel2.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(), "De aprendizaje"));

        jLabel_AlfaG.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_AlfaG.setText("Alfa global (%)");
        jPanel2.add(jLabel_AlfaG, new AbsoluteConstraints(20, 30, 140, -1));

        jLabel_Profundidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Profundidad.setText("Profundidad");
        jPanel2.add(jLabel_Profundidad, new AbsoluteConstraints(20, 70, 140, -1));

        jLabel_GIM.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_GIM.setText("% Ganancia de Inf m\u00ednima");
        jLabel_GIM.setToolTipText("Porcentage de Ganancia de Informaci\u00f3n M\u00ednima");
        jPanel2.add(jLabel_GIM, new AbsoluteConstraints(20, 110, -1, -1));

        jTextField_AlfaG.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_AlfaG.setText("1");
        jPanel2.add(jTextField_AlfaG, new AbsoluteConstraints(170, 30, 60, -1));

        jTextField_Profundidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_Profundidad.setText("1");
        jPanel2.add(jTextField_Profundidad, new AbsoluteConstraints(170, 70, 60, -1));

        jTextField_GIM.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_GIM.setText("1");
        jPanel2.add(jTextField_GIM, new AbsoluteConstraints(170, 110, 60, -1));

        getContentPane().add(jPanel2, new AbsoluteConstraints(260, 10, 250, 150));

        // ------------------------------- BOTONES

        Btn_Aceptar.setText("Aceptar");
        Btn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AceptarActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Aceptar, new AbsoluteConstraints(160, 170, -1, -1));


        Btn_Cancelar.setText("Cancelar");
        Btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Cancelar, new AbsoluteConstraints(270, 170, -1, -1));

        pack();
    }//GEN-END:initComponents
// -----------------------------------------------------------------------------
    private void LeeDatos() {
      DecimalFormat df = new DecimalFormat( "#" );
      Variables = new Integer( hta.bPE.numVariables );
      Casos     = new Integer( hta.bPE.Casos        );
      Decimales = new Integer( hta.bPE.Decimales    );

      AlfaG       = new Double(  hta.bPE.alfaG * 100 ); 
      Profundidad = new Integer( hta.bPE.profundidad );
      GIM         = new Double(  hta.bPE.minPorcGan  );  //Ganancia de Informacion Mínima

      jTextField_Variables.setText( Variables.toString() ); 
      jTextField_Casos.setText(     Casos.toString()     ); 
      jTextField_Decimales.setText( Decimales.toString() ); 

      jTextField_AlfaG.setText( df.format( AlfaG.doubleValue() ) ); 
      jTextField_Profundidad.setText( Profundidad.toString()     );
      //jTextField_GIM.setText(   df.format( GIM.doubleValue()   ) );
      jTextField_GIM.setText(   GIM.toString()  );
   }
// -----------------------------------------------------------------------------
    private void Btn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {                                            
      AlfaG       = new Double(  jTextField_AlfaG.getText()       );
      Profundidad = new Integer( jTextField_Profundidad.getText() );
      GIM         = new Double(  jTextField_GIM.getText()         );  //Ganancia de Informacion Mínima
      Decimales   = new Integer( jTextField_Decimales.getText()   );

      hta.bPE.alfaG       = AlfaG.doubleValue() / 100;
      hta.bPE.profundidad = Profundidad.intValue();
      hta.bPE.minPorcGan  = GIM.doubleValue();
      hta.bPE.Decimales   = Decimales.intValue();

      hta.bPE.PatronDecimales = "#0.";
      for( int k = 1; k <= hta.bPE.Decimales; k++) hta.bPE.PatronDecimales += "0";
      setVisible(false); dispose();
    }
// -----------------------------------------------------------------------------
    private void Btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        setVisible(false); dispose();
    }
// -----------------------------------------------------------------------------
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {                             
        setVisible(false); dispose();
    }
// -----------------------------------------------------------------------------
    /**
     * @param args the command line arguments
     */
/*    public static void main(String args[]) {
        new VdParametros(new javax.swing.JFrame(), true).show();
    }
*/
// -----------------------------------------------------------------------------
    // Variables 

    public frmPrincipal hta;
    public Integer Variables;
    public Integer Casos;
    public Integer Decimales;
    public Double  AlfaG;
    public Integer Profundidad;
    public Double  GIM; //Ganancia de Informacion Mínima

    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jLabel_Variables;     
    private javax.swing.JLabel jLabel_Casos;
    private javax.swing.JLabel jLabel_Decimales;
    private javax.swing.JTextField jTextField_Variables;
    private javax.swing.JTextField jTextField_Casos;
    private javax.swing.JTextField jTextField_Decimales;

    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jLabel_AlfaG;
    private javax.swing.JLabel jLabel_Profundidad;
    private javax.swing.JLabel jLabel_GIM;
    private javax.swing.JTextField jTextField_AlfaG;
    private javax.swing.JTextField jTextField_Profundidad;
    private javax.swing.JTextField jTextField_GIM;

    private javax.swing.JButton Btn_Aceptar;
    private javax.swing.JButton Btn_Cancelar;

    // End of variables declaration                   
    
}
// -----------------------------------------------------------------------------
