/*
 * frmPrincipal.java
 *
 * Created on 5 de octubre de 2006, 14:13
 */

package bansy21;

import java.awt.*;
import java.io.File;
import java.awt.event.*;
import java.io.FileOutputStream;
import java.util.Vector;
import java.util.Calendar;
import javax.imageio.stream.FileImageInputStream;
import javax.swing.*;
import javax.swing.event.InternalFrameListener;
import javax.swing.event.InternalFrameEvent;
import java.lang.Thread;

import bansy21.Utilerias.*;
import bansy21.Red.*;
import bansy21.Algoritmos.*;
import bansy21.Metricas.*;
import bansy21.Inferencia.*;
import bansy21.Clasificacion.*;
import bansy21.Gui.*;

/**
 *
 * @author  jjimenez
 */
public class frmPrincipal extends javax.swing.JFrame {
    
        public ImageIcon icon=new javax.swing.ImageIcon(getClass().getResource("/images/mia.ico"));
              
        public  JFileChooser chooser;
	public JStatusBar statusBar;
        
        public JMenuItemExtended[] ventanas;
        
    	//clase encargada de obtener los eventos
	EventHelper eventListener;
        
        //objeto para usar las utilerias
	public Utilerias util;	
        
        //Codificador para guardar el proyecto
        public bansyProyEcoder bPE=null;
        
        public OutPut sal=null;
	public Progress pMonitor=null;
        
        public JointProbability jp=null;
	public InferenciaGeneral ig=null;
        
    /** Creates new form frmPrincipal */
    public frmPrincipal() {
       
        //setDefaultLookAndFeelDecorated(true);			
	//String lnfName =	"com.sun.java.swing.plaf.motif.MotifLookAndFeel";
	//String lnfName =	"com.sun.java.swing.plaf.basic.BasicLookAndFeel";
	//String lnfName =	"com.sun.java.swing.plaf.multi.MultiLookAndFeel";
	String lnfName = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
	//String lnfName ="javax.swing.plaf.metal.MetalLookAndFeel";
        
         try 
		{
			UIManager.setLookAndFeel(lnfName);
		  SwingUtilities.updateComponentTreeUI(this);
		 // this.pack();
		} catch (Exception exc) {}
        bPE=new bansyProyEcoder();
        util=new Utilerias();
        eventListener=new EventHelper();
       // this.setIconImage(icono);
       initComponents(); 
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jToolBar1 = new javax.swing.JToolBar();
        btnToolbarNuevo = new javax.swing.JButton();
        btnTollAbrir1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        desktop = new javax.swing.JDesktopPane();
        jmenuPrincipal = new javax.swing.JMenuBar();
        jmArchivo = new javax.swing.JMenu();
        jmCargarDatos = new javax.swing.JMenuItem();
        jmLeer = new javax.swing.JMenu();
        jmLeerArc = new javax.swing.JMenuItem();
        jmLeerArcElvira = new javax.swing.JMenuItem();
        jmLeerRedXML = new javax.swing.JMenuItem();
        jmGuardar = new javax.swing.JMenu();
        jmGuarArcos = new javax.swing.JMenuItem();
        jmGuarDatElvira = new javax.swing.JMenuItem();
        jmGuarDatArrf = new javax.swing.JMenuItem();
        jmConvDNET = new javax.swing.JMenuItem();
        jmCerrarVent = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmVer = new javax.swing.JMenu();
        jmParametros = new javax.swing.JMenuItem();
        jmAprendizaje = new javax.swing.JMenu();
        jmBayesN = new javax.swing.JMenuItem();
        jmBayes9 = new javax.swing.JMenuItem();
        jmMP = new javax.swing.JMenuItem();
        jmBayes2 = new javax.swing.JMenuItem();
        jmBayes5 = new javax.swing.JMenuItem();
        jmBayesNn = new javax.swing.JMenuItem();
        jmNaive = new javax.swing.JMenuItem();
        jmProbabilidades = new javax.swing.JMenu();
        jmTabProbCond = new javax.swing.JMenuItem();
        jmTabProbGral = new javax.swing.JMenuItem();
        jmInferencia = new javax.swing.JMenu();
        jmInfGral = new javax.swing.JMenuItem();
        jmInfNaive = new javax.swing.JMenuItem();
        jmAjuste = new javax.swing.JMenu();
        jmMBayesiana = new javax.swing.JMenuItem();
        jmMDL = new javax.swing.JMenuItem();
        jmMDLNilsson = new javax.swing.JMenuItem();
        jmClasificacion = new javax.swing.JMenu();
        jmHoldOut = new javax.swing.JMenuItem();
        jmCrossVal = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        jmClasFamBayes = new javax.swing.JMenuItem();
        jmClasNaive = new javax.swing.JMenuItem();
        jmVentana = new javax.swing.JMenu();
        jmMenuOrgVen = new javax.swing.JMenu();
        jmMenuCascada = new javax.swing.JMenuItem();
        jmMenuRejilla = new javax.swing.JMenuItem();
        jmMenuMosaicoHorizontal = new javax.swing.JMenuItem();
        jmMenuMosaicoVertical = new javax.swing.JMenuItem();
        imMenuMinimizar = new javax.swing.JMenuItem();
        jmMenuRestaurar = new javax.swing.JMenuItem();
        jmMenuMaximizar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BANSY 3");
        setName("BANSY 3");
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        btnToolbarNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nuevos/NewDocumentHS.png")));
        btnToolbarNuevo.setToolTipText("Nueva red");
        btnToolbarNuevo.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/New24.gif")));
        btnToolbarNuevo.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/New24.gif")));
        btnToolbarNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToolbarNuevoActionPerformed(evt);
            }
        });

        jToolBar1.add(btnToolbarNuevo);

        btnTollAbrir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nuevos/file.gif")));
        btnTollAbrir1.setToolTipText("Abrir archivo de texto");
        btnTollAbrir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTollAbrir1ActionPerformed(evt);
            }
        });

        jToolBar1.add(btnTollAbrir1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nuevos/nodeblueligth.png")));
        jButton2.setToolTipText("Nuevo Nodo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nuevos/arco.png")));
        jButton3.setToolTipText("Nuevo Arco");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jToolBar1.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nuevos/remove_16.png")));
        jButton4.setToolTipText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jToolBar1.add(jButton4);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        desktop.setBackground(new java.awt.Color(204, 204, 204));
        desktop.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                desktopComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                componenteRemovido(evt);
            }
        });

        getContentPane().add(desktop, java.awt.BorderLayout.CENTER);

        jmArchivo.setText("Archivo");
        jmCargarDatos.setText("Cargar Datos");
        jmCargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCargarDatosActionPerformed(evt);
            }
        });

        jmArchivo.add(jmCargarDatos);

        jmLeer.setLabel("Leer");
        jmLeerArc.setLabel("Leer Arcos");
        jmLeerArc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmLeerArcActionPerformed(evt);
            }
        });

        jmLeer.add(jmLeerArc);

        jmLeerArcElvira.setText("Leer Arcos Elvira");
        jmLeerArcElvira.setEnabled(false);
        jmLeerArcElvira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmLeerArcElviraActionPerformed(evt);
            }
        });

        jmLeer.add(jmLeerArcElvira);

        jmLeerRedXML.setText("Leer Red  XML");
        jmLeerRedXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmLeerRedXMLActionPerformed(evt);
            }
        });

        jmLeer.add(jmLeerRedXML);

        jmArchivo.add(jmLeer);

        jmGuardar.setText("Guardar");
        jmGuarArcos.setText("Guardas Arcos");
        jmGuarArcos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmGuarArcosActionPerformed(evt);
            }
        });

        jmGuardar.add(jmGuarArcos);

        jmGuarDatElvira.setText("Guardar Datos en Formato Elvira");
        jmGuarDatElvira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmGuarDatElviraActionPerformed(evt);
            }
        });

        jmGuardar.add(jmGuarDatElvira);

        jmGuarDatArrf.setText("Guardar Datos en Formato arrf");
        jmGuarDatArrf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmGuarDatArrfActionPerformed(evt);
            }
        });

        jmGuardar.add(jmGuarDatArrf);

        jmArchivo.add(jmGuardar);

        jmConvDNET.setText("Convertir formato DNET a arcos simples");
        jmConvDNET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConvDNETActionPerformed(evt);
            }
        });

        jmArchivo.add(jmConvDNET);

        jmCerrarVent.setText("Cerrar ventanas");
        jmCerrarVent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCerrarVentActionPerformed(evt);
            }
        });

        jmArchivo.add(jmCerrarVent);

        jmArchivo.add(jSeparator1);

        jMenuItem2.setLabel("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });

        jmArchivo.add(jMenuItem2);

        jmenuPrincipal.add(jmArchivo);

        jmVer.setText("Ver");
        jmParametros.setText("Par\u00e1metros...");
        jmParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmParametrosActionPerformed(evt);
            }
        });

        jmVer.add(jmParametros);

        jmenuPrincipal.add(jmVer);

        jmAprendizaje.setText("Aprendizaje");
        jmBayesN.setText("Bayes N");
        jmBayesN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmBayesNActionPerformed(evt);
            }
        });

        jmAprendizaje.add(jmBayesN);

        jmBayes9.setText("Bayes 9");
        jmBayes9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmBayes9ActionPerformed(evt);
            }
        });

        jmAprendizaje.add(jmBayes9);

        jmMP.setText("MP Bayes");
        jmMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMPActionPerformed(evt);
            }
        });

        jmAprendizaje.add(jmMP);

        jmBayes2.setText("Bayes 2");
        jmBayes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmBayes2ActionPerformed(evt);
            }
        });

        jmAprendizaje.add(jmBayes2);

        jmBayes5.setText("Bayes 5");
        jmBayes5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmBayes5ActionPerformed(evt);
            }
        });

        jmAprendizaje.add(jmBayes5);

        jmBayesNn.setText("Bayes Nn");
        jmBayesNn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmBayesNnActionPerformed(evt);
            }
        });

        jmAprendizaje.add(jmBayesNn);

        jmNaive.setText("Na\u00efve Bayes");
        jmNaive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmNaiveActionPerformed(evt);
            }
        });

        jmAprendizaje.add(jmNaive);

        jmenuPrincipal.add(jmAprendizaje);

        jmProbabilidades.setText("Probailidades");
        jmTabProbCond.setText("Tablas de probailidades condicionales");
        jmTabProbCond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTabProbCondActionPerformed(evt);
            }
        });

        jmProbabilidades.add(jmTabProbCond);

        jmTabProbGral.setText("Tabla general de probabilidades");
        jmTabProbGral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTabProbGralActionPerformed(evt);
            }
        });

        jmProbabilidades.add(jmTabProbGral);

        jmenuPrincipal.add(jmProbabilidades);

        jmInferencia.setText("Inferencia");
        jmInfGral.setText("M\u00e9todo General");
        jmInfGral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmInfGralActionPerformed(evt);
            }
        });

        jmInferencia.add(jmInfGral);

        jmInfNaive.setText("Na\u00efve");
        jmInfNaive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmInfNaiveActionPerformed(evt);
            }
        });

        jmInferencia.add(jmInfNaive);

        jmenuPrincipal.add(jmInferencia);

        jmAjuste.setText("Ajuste");
        jmMBayesiana.setText("M\u00e9trica Bayesiana");
        jmMBayesiana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMBayesianaActionPerformed(evt);
            }
        });

        jmAjuste.add(jmMBayesiana);

        jmMDL.setText("MDL");
        jmMDL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMDLActionPerformed(evt);
            }
        });

        jmAjuste.add(jmMDL);

        jmMDLNilsson.setText("MDL (Nilsson)");
        jmMDLNilsson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMDLNilssonActionPerformed(evt);
            }
        });

        jmAjuste.add(jmMDLNilsson);

        jmenuPrincipal.add(jmAjuste);

        jmClasificacion.setText("Clasificaci\u00f3n");
        jmHoldOut.setText("Hold-Out");
        jmHoldOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmHoldOutActionPerformed(evt);
            }
        });

        jmClasificacion.add(jmHoldOut);

        jmCrossVal.setText("Cross-Validation");
        jmCrossVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCrossValActionPerformed(evt);
            }
        });

        jmClasificacion.add(jmCrossVal);

        jmClasificacion.add(jSeparator2);

        jmClasFamBayes.setText("Clasificaci\u00f3n (familia bayes)");
        jmClasFamBayes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmClasFamBayesActionPerformed(evt);
            }
        });

        jmClasificacion.add(jmClasFamBayes);

        jmClasNaive.setText("Clasificaci\u00f3n (Naive)");
        jmClasNaive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmClasNaiveActionPerformed(evt);
            }
        });

        jmClasificacion.add(jmClasNaive);

        jmenuPrincipal.add(jmClasificacion);

        jmVentana.setText("Ventana");
        jmMenuOrgVen.setText("Organiza Ventanas");
        jmMenuCascada.setText("Cascada");
        jmMenuCascada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMenuCascadaActionPerformed(evt);
            }
        });

        jmMenuOrgVen.add(jmMenuCascada);

        jmMenuRejilla.setText("Rejilla");
        jmMenuRejilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMenuRejillaActionPerformed(evt);
            }
        });

        jmMenuOrgVen.add(jmMenuRejilla);

        jmMenuMosaicoHorizontal.setText("Mosaico Horizantal");
        jmMenuMosaicoHorizontal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMenuMosaicoHorizontalActionPerformed(evt);
            }
        });

        jmMenuOrgVen.add(jmMenuMosaicoHorizontal);

        jmMenuMosaicoVertical.setText("Mosaico Vertical");
        jmMenuMosaicoVertical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMenuMosaicoVerticalActionPerformed(evt);
            }
        });

        jmMenuOrgVen.add(jmMenuMosaicoVertical);

        imMenuMinimizar.setText("Minimizar");
        imMenuMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imMenuMinimizarActionPerformed(evt);
            }
        });

        jmMenuOrgVen.add(imMenuMinimizar);

        jmMenuRestaurar.setText("Restaurar");
        jmMenuRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMenuRestaurarActionPerformed(evt);
            }
        });

        jmMenuOrgVen.add(jmMenuRestaurar);

        jmMenuMaximizar.setText("Maximizar");
        jmMenuMaximizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMenuMaximizarActionPerformed(evt);
            }
        });

        jmMenuOrgVen.add(jmMenuMaximizar);

        jmVentana.add(jmMenuOrgVen);

        jmenuPrincipal.add(jmVentana);

        setJMenuBar(jmenuPrincipal);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-800)/2, (screenSize.height-600)/2, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void jmMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMPActionPerformed
// TODO add your handling code here:
        MP();
    }//GEN-LAST:event_jmMPActionPerformed

    private void desktopComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_desktopComponentAdded
// TODO add your handling code here:
    }//GEN-LAST:event_desktopComponentAdded

    private void btnTollAbrir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTollAbrir1ActionPerformed
// TODO add your handling code here:
         cargarDatos();
    }//GEN-LAST:event_btnTollAbrir1ActionPerformed

   
    private void componenteRemovido(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_componenteRemovido
// TODO add your handling code here:
        //jmVentana.remove(evt.getComponent());
    }//GEN-LAST:event_componenteRemovido

    private void jmMenuMaximizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMenuMaximizarActionPerformed
// TODO add your handling code here:
        VenOrgMenuMaximizar();
    }//GEN-LAST:event_jmMenuMaximizarActionPerformed

    private void jmMenuRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMenuRestaurarActionPerformed
// TODO add your handling code here:
        VenOrgMenuRestaurar();
    }//GEN-LAST:event_jmMenuRestaurarActionPerformed

    private void imMenuMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imMenuMinimizarActionPerformed
// TODO add your handling code here:
        VenOrgMenuMinimizar();
    }//GEN-LAST:event_imMenuMinimizarActionPerformed

    private void jmMenuMosaicoVerticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMenuMosaicoVerticalActionPerformed
// TODO add your handling code here:
        VenOrgMenuMosaicoVertical();
    }//GEN-LAST:event_jmMenuMosaicoVerticalActionPerformed

    private void jmMenuMosaicoHorizontalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMenuMosaicoHorizontalActionPerformed
// TODO add your handling code here:
        VenOrgMenuMosaicoHorizontal();
    }//GEN-LAST:event_jmMenuMosaicoHorizontalActionPerformed

    private void jmMenuRejillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMenuRejillaActionPerformed
// TODO add your handling code here:
        VenOrgMenuRejilla();
    }//GEN-LAST:event_jmMenuRejillaActionPerformed

    private void jmMenuCascadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMenuCascadaActionPerformed
// TODO add your handling code here:
        VenOrgMenuCascada();
    }//GEN-LAST:event_jmMenuCascadaActionPerformed

    private void jmClasNaiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmClasNaiveActionPerformed
// TODO add your handling code here:
        naiveClasification();
    }//GEN-LAST:event_jmClasNaiveActionPerformed

    private void jmClasFamBayesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmClasFamBayesActionPerformed
// TODO add your handling code here:
        generalClasificacion();
    }//GEN-LAST:event_jmClasFamBayesActionPerformed

    private void jmCrossValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCrossValActionPerformed
// TODO add your handling code here:
        crossVal();
    }//GEN-LAST:event_jmCrossValActionPerformed

    private void jmHoldOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmHoldOutActionPerformed
// TODO add your handling code here:
        holdOut();
    }//GEN-LAST:event_jmHoldOutActionPerformed

    private void jmMDLNilssonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMDLNilssonActionPerformed
// TODO add your handling code here:
        MDLNMatric();
    }//GEN-LAST:event_jmMDLNilssonActionPerformed

    private void jmMDLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMDLActionPerformed
// TODO add your handling code here:
        MDLMatric();
    }//GEN-LAST:event_jmMDLActionPerformed

    private void jmMBayesianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMBayesianaActionPerformed
// TODO add your handling code here:
        bayesianMeasure();
    }//GEN-LAST:event_jmMBayesianaActionPerformed

    private void jmInfNaiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmInfNaiveActionPerformed
// TODO add your handling code here:
        naiveInferenceM();
    }//GEN-LAST:event_jmInfNaiveActionPerformed

    private void jmInfGralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmInfGralActionPerformed
// TODO add your handling code here:
       
       inferenciaGeneral();
    }//GEN-LAST:event_jmInfGralActionPerformed

    private void jmTabProbGralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTabProbGralActionPerformed
// TODO add your handling code here:
        probabilityDistribution();
    }//GEN-LAST:event_jmTabProbGralActionPerformed

    private void jmTabProbCondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTabProbCondActionPerformed
// TODO add your handling code here:
        probability();
    }//GEN-LAST:event_jmTabProbCondActionPerformed

    private void jmNaiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmNaiveActionPerformed
// TODO add your handling code here:
        naiveBayes();
    }//GEN-LAST:event_jmNaiveActionPerformed

    private void jmBayesNnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBayesNnActionPerformed
// TODO add your handling code here:
        bayesNn();
    }//GEN-LAST:event_jmBayesNnActionPerformed

    private void jmBayes5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBayes5ActionPerformed
// TODO add your handling code here:
        bayes2();
    }//GEN-LAST:event_jmBayes5ActionPerformed

    private void jmBayes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBayes2ActionPerformed
// TODO add your handling code here:
        bayes2();
    }//GEN-LAST:event_jmBayes2ActionPerformed

    private void jmBayes9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBayes9ActionPerformed
// TODO add your handling code here:
        bayes9();
    }//GEN-LAST:event_jmBayes9ActionPerformed

    private void jmBayesNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBayesNActionPerformed
// TODO add your handling code here:
        bayesN();
    }//GEN-LAST:event_jmBayesNActionPerformed

    private void jmParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmParametrosActionPerformed
// TODO add your handling code here:
        VerParametros();
    }//GEN-LAST:event_jmParametrosActionPerformed

    private void jmCerrarVentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCerrarVentActionPerformed
// TODO add your handling code here:
        CierraVentanas();
    }//GEN-LAST:event_jmCerrarVentActionPerformed

    private void jmConvDNETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConvDNETActionPerformed
// TODO add your handling code here:
        convertir();
    }//GEN-LAST:event_jmConvDNETActionPerformed

    private void jmGuarDatArrfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmGuarDatArrfActionPerformed
// TODO add your handling code here:
        guardarArff();
    }//GEN-LAST:event_jmGuarDatArrfActionPerformed

    private void jmGuarDatElviraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmGuarDatElviraActionPerformed
// TODO add your handling code here:
        guardarBaseElvM();
    }//GEN-LAST:event_jmGuarDatElviraActionPerformed

    private void jmGuarArcosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmGuarArcosActionPerformed
// TODO add your handling code here:
        guardarArcosM();
    }//GEN-LAST:event_jmGuarArcosActionPerformed

    private void jmLeerRedXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmLeerRedXMLActionPerformed
// TODO add your handling code here:
        leerRedXMLM();
    }//GEN-LAST:event_jmLeerRedXMLActionPerformed

    private void jmLeerArcElviraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmLeerArcElviraActionPerformed
// TODO add your handling code here:
        leerArcosElvira();
    }//GEN-LAST:event_jmLeerArcElviraActionPerformed

    private void jmLeerArcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmLeerArcActionPerformed
// TODO add your handling code here:
        leerArcosM();
    }//GEN-LAST:event_jmLeerArcActionPerformed

    private void jmCargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCargarDatosActionPerformed
// TODO add your handling code here:
        cargarDatos();
    }//GEN-LAST:event_jmCargarDatosActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
        borrar();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
        agregarArco();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
        agregarNodo();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnToolbarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToolbarNuevoActionPerformed
// TODO add your handling code here:
        nuevaRed();
    }//GEN-LAST:event_btnToolbarNuevoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
// TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTollAbrir1;
    private javax.swing.JButton btnToolbarNuevo;
    public javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem imMenuMinimizar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu jmAjuste;
    private javax.swing.JMenu jmAprendizaje;
    private javax.swing.JMenu jmArchivo;
    private javax.swing.JMenuItem jmBayes2;
    private javax.swing.JMenuItem jmBayes5;
    private javax.swing.JMenuItem jmBayes9;
    private javax.swing.JMenuItem jmBayesN;
    private javax.swing.JMenuItem jmBayesNn;
    private javax.swing.JMenuItem jmCargarDatos;
    private javax.swing.JMenuItem jmCerrarVent;
    private javax.swing.JMenuItem jmClasFamBayes;
    private javax.swing.JMenuItem jmClasNaive;
    private javax.swing.JMenu jmClasificacion;
    private javax.swing.JMenuItem jmConvDNET;
    private javax.swing.JMenuItem jmCrossVal;
    private javax.swing.JMenuItem jmGuarArcos;
    private javax.swing.JMenuItem jmGuarDatArrf;
    private javax.swing.JMenuItem jmGuarDatElvira;
    private javax.swing.JMenu jmGuardar;
    private javax.swing.JMenuItem jmHoldOut;
    private javax.swing.JMenuItem jmInfGral;
    private javax.swing.JMenuItem jmInfNaive;
    private javax.swing.JMenu jmInferencia;
    private javax.swing.JMenu jmLeer;
    private javax.swing.JMenuItem jmLeerArc;
    private javax.swing.JMenuItem jmLeerArcElvira;
    private javax.swing.JMenuItem jmLeerRedXML;
    private javax.swing.JMenuItem jmMBayesiana;
    private javax.swing.JMenuItem jmMDL;
    private javax.swing.JMenuItem jmMDLNilsson;
    private javax.swing.JMenuItem jmMP;
    private javax.swing.JMenuItem jmMenuCascada;
    private javax.swing.JMenuItem jmMenuMaximizar;
    private javax.swing.JMenuItem jmMenuMosaicoHorizontal;
    private javax.swing.JMenuItem jmMenuMosaicoVertical;
    private javax.swing.JMenu jmMenuOrgVen;
    private javax.swing.JMenuItem jmMenuRejilla;
    private javax.swing.JMenuItem jmMenuRestaurar;
    private javax.swing.JMenuItem jmNaive;
    private javax.swing.JMenuItem jmParametros;
    private javax.swing.JMenu jmProbabilidades;
    private javax.swing.JMenuItem jmTabProbCond;
    private javax.swing.JMenuItem jmTabProbGral;
    private javax.swing.JMenu jmVentana;
    private javax.swing.JMenu jmVer;
    private javax.swing.JMenuBar jmenuPrincipal;
    // End of variables declaration//GEN-END:variables
    
    
    private void setInitD()
	{
		chooser=new JFileChooser();
		File f=new File("./");
		if (f.exists())
		{
			chooser.setCurrentDirectory(f);
		}
	}
	
	/**
	* Inicializa el dialogo en el que se depliegan mensajes, y l mmuestra
	*/
	private void initOutPut(String title)
	{
		sal=new OutPut(this,title);
		sal.show();
	}
    private void establecerIcono()
    {       
        javax.swing.ImageIcon ico = new javax.swing.ImageIcon("/images/mia.jpg");
        
    }
    
   
    
    
    public void createMenuVentana()
	{
           // if(jmVentana!= null)
           //   jmenuPrincipal.remove(jmVentana);
            
            jmVentana.removeAll();
            jmVentana.add(jmMenuOrgVen);
            jmVentana.add(new JSeparator());

            JInternalFrame[] frames=desktop.getAllFrames();
            ventanas=new JMenuItemExtended[frames.length];
//		for (int i=0;i<frames.length;i++)
            for ( int i=frames.length-1; i >= 0; i-- )
		{
//			ventanas[i]=new JMenuItemExtended(((RedFrame)frames[i]).redPanel.red.name+i);  
//			ventanas[i]=new JMenuItemExtended( frames[i].getTitle() );

			ventanas[i]=new JMenuItemExtended( ((JInternalFrame) frames[i]).getTitle() );
			try{
				ventanas[i].InternalFrame = frames[i];
				ventanas[i].red=((RedFrame)frames[i]);

			} catch( Exception e ) {System.out.println("CreateMenuVentana: esta ventana no es red"); }
			System.out.println("CreateMenuVentana: Agrega ActionListener");
			ventanas[i].addActionListener(eventListener);
			jmVentana.add(ventanas[i]);
		}
		//jmenuPrincipal.add(jmVentana);
            //setJMenuBar( b_menu );
	      // pack();
	}
// -----------------------------------------------------------------------------------------------
  
    public void CierraVentanas()
  {
    JInternalFrame[] frames=desktop.getAllFrames();
    for ( int i=frames.length-1; i >= 0; i-- )
    {
	try{
	  frames[i].setClosed( true );
      } catch( Exception e ) {}
    }
    createMenuVentana();
  }
    
    
    
    // ----------------------------------------------------------------------------------------------
	//agregar un red en blaco
	private void nuevaRed()
	{
		//Mostar al usuario una ventana en la que introduza el nombre de la red, y otros atributos si es
		//necesario
		agregarRed("Nueva Red");
	}
// ----------------------------------------------------------------------------------------------
	//para avisarle al rame que ponga un nodo
	private void agregarNodo()
	{
		RedFrame redF=(RedFrame)desktop.getSelectedFrame();
		if(redF!=null)
		{			
			redF.redPanel.newNode=true;
		}
		else
		{			
			//enviar un mensaje en el que le diga que debe agregar un red nueva antes
			JOptionPane.showMessageDialog(this,"There is not any selected network","Network",JOptionPane.INFORMATION_MESSAGE);
		}
	}
	//para avisarle al frame que ponga un arco
	private void agregarArco()
	{
		RedFrame redF=(RedFrame)desktop.getSelectedFrame();
		if(redF!=null)
		{
			if(redF.redPanel.numVariables>1)
				redF.redPanel.newArco=true;
		}
		else
		{			
			//enviar un mensaje en el que le diga que debe agregar un red nueva antes
			JOptionPane.showMessageDialog(this,"No ha seleccionado una red. Seleccione la ventana que contiene la red bayesiana que sea evaluar","Error en la selección",JOptionPane.INFORMATION_MESSAGE);
		}
	}

	//este metodo se llama cuando se presiona el boton de borrar, y lo que
	//hace es verificar si algon elemento de la red esta seleccionado, si asi es,
	//trata de borrarlo
	private void borrar()
	{
		RedFrame redF=(RedFrame)desktop.getSelectedFrame();
		if(redF!=null)
		{
			if(redF.redPanel.selectedN!=null)
			{
				//quiere decir que esta seleccionado un nodo
				//hay que remover tods los arcos en los que participaba este nodo
				Arco temp=redF.redPanel.red.inArco;
				if(temp!=null)
				{
					do
					{
						if(temp.from.name.equals(redF.redPanel.selectedN.name) || temp.to.name.equals(redF.redPanel.selectedN.name))
						{
							redF.redPanel.red.inArco=util.remove(temp,redF.redPanel.red.inArco);
						}
						temp=temp.sig;
					}
					while (temp!=null);
				}								
				redF.redPanel.red.inicio=util.removeNode(redF.redPanel.selectedN,redF.redPanel.red.inicio);				
				redF.redPanel.selectedN=null;
				redF.redPanel.repaint();
			}
			if(redF.redPanel.selectedA!=null)
			{
				//quiere decir que esta seleccionado un arco				
				redF.redPanel.red.inArco=util.remove(redF.redPanel.selectedA,redF.redPanel.red.inArco);
				redF.redPanel.selectedA=null;
				redF.redPanel.repaint();
			}

		}
		else
		{			
			//enviar un mensaje en el que le diga que debe agregar un red nueva antes
			JOptionPane.showMessageDialog(this,"No ha seleccionado una red. Seleccione la ventana que contiene la red bayesiana que sea evaluar","Error en la selección",JOptionPane.INFORMATION_MESSAGE);
		}
	}

	private void probability()
	{
		
		if((desktop.getSelectedFrame())!=null)//
		{
                    RedFrame redF=(RedFrame)desktop.getSelectedFrame();
			if(bPE.casos!=null)
			{
				ProbInf pro=new ProbInf();
				pro.casos=bPE.casos;
				redF.redPanel.red=pro.probabilityTables(redF.redPanel.red);
			}
		}
		else
		{
			//enviar un mensaje en el que le diga que debe agregar un red nueva antes
			JOptionPane.showMessageDialog(this,"No ha seleccionado una red. Seleccione la ventana que contiene la red bayesiana que sea evaluar","Error en la selección",JOptionPane.INFORMATION_MESSAGE);
		}
	}
//-----------------------------------------------------------------------------------------
	private void probabilityDistribution()
	{	
           
		if((desktop.getSelectedFrame())!=null && (desktop.getSelectedFrame()).getClass().getName().equals("bansy21.Gui.RedFrame") && bPE.casos!=null)//
		{	
                    RedFrame redF=(RedFrame)desktop.getSelectedFrame();		
			jp=new JointProbability(redF.redPanel.red,bPE.casos);			
			//jp.generate();
			jp.generateFromRed();

			ShowerTable st=new ShowerTable(this,jp.comb,jp.table,redF.redPanel.red);

			// Agregada por AAT
			desktop.add(st);
			try {	
				st.setMaximum(true); 
			}catch(Exception e){};
			try {
				st.setSelected(true);
			} catch (java.beans.PropertyVetoException e) {}
		}
		else
		{
			if (bPE.inicio!=null && bPE.casos!=null)
			{
                             RedFrame redF=(RedFrame)desktop.getSelectedFrame();		
				Red  red= new Red();
				red.inicio=bPE.inicio;
				jp=new JointProbability(red,bPE.casos);				
				jp.generate();
				ShowerTable st=new ShowerTable(this,jp.comb,jp.table,redF.redPanel.red);

				// Agregada por AAT
				desktop.add(st);
				try {	
					st.setMaximum(true); 
				}catch(Exception e){};
				try {
					st.setSelected(true);
				} catch (java.beans.PropertyVetoException e) {}
			}
			else
			{
				//enviar un mensaje en el que le diga que debe agregar un red nueva antes
				JOptionPane.showMessageDialog(this,"No ha seleccionado una red. Seleccione la ventana que contiene la red bayesiana que sea evaluar","Error en la selección",JOptionPane.INFORMATION_MESSAGE);
			}
		}
// Agregada por AAT
		createMenuVentana();

	}
//-----------------------------------------------------------------------------------------
	/**
	* Método de inferencia general
	*/
	private void inferenciaGeneral()
	{
		/*
		
		si no se ha calculado la tabla de probabilidades a partir de la red bayesiana
		entonces calcularla

		ya que se tiene la tabla, mostrar una ventana con el nodo consulta, y en un comboBox los valores 
		que puede tomar el nodo, para que el usuario seleccione uno, lo mismo se hace para los nodos evidencia
		(un combo para cada uno)

		ya que se selecciono, entonces echar a andar el metodo para calcular la probabildiad, que prodria ser 
		en la misma ventana, de esta forma el usuario pórdria cambiar los valores y recalcular
		si quiere agregar mas nodos de evidencia, entonces tendra que cerrar la ventana	

		*/
		
		
		if((desktop.getSelectedFrame())!=null && (desktop.getSelectedFrame()).getClass().getName().equals("bansy21.Gui.RedFrame") && jp!=null)//
		{
			RedFrame redF=(RedFrame)desktop.getSelectedFrame();
         
         /*
         createMonitor("Inferencia",true,jp.comb.length);
			InferenciaGeneral infG=new InferenciaGeneral();
			infG.jp=jp;
			jp.pMonitor=pMonitor;
			infG.pMonitor=pMonitor;
			infG.red=redF.redPanel.red;
			infG.start();
			*/
        
         jframeInference jfr= new bansy21.Gui.jframeInference(redF.redPanel.red);
         jfr.jp=jp;
         
         jfr.show();
         
         desktop.add(jfr);
         createMenuVentana();
         desktop.setSelectedFrame(jfr);
		}
		else
		{
			//enviar un mensaje en el que le diga que debe agregar un red nueva antes
			JOptionPane.showMessageDialog(this,"No ha seleccionado una red. Seleccione la ventana que contiene la red bayesiana que sea evaluar","Error en la selección",JOptionPane.INFORMATION_MESSAGE);
		}


	}

	/**
	*Calcula la medida Bayesiana para la red
	*/
	private void bayesianMeasure()
	{
		
		if((desktop.getSelectedFrame())!=null && (desktop.getSelectedFrame()).getClass().getName().equals("bansy21.Gui.RedFrame"))//
		{
                    RedFrame redF=(RedFrame)desktop.getSelectedFrame();
			if(bPE.casos!=null && redF.redPanel.red.inicio.parents!=null)
			{
				BMeasure bm=new BMeasure();
				bm.red=redF.redPanel.red;
				bm.casos=bPE.casos;
				createMonitor("Métrica Bayesiana", true, bPE.casos.size()+bPE.numVariables);
				bm.pMonitor=pMonitor;
				bm.start();
                                this.setSelectedFrame(pMonitor);
                                
			}
		}
		else
		{
			//enviar un mensaje en el que le diga que debe agregar un red nueva antes
			JOptionPane.showMessageDialog(this,"No ha seleccionado una red. Seleccione la ventana que contiene la red bayesiana que sea evaluar","Error en la selección",JOptionPane.INFORMATION_MESSAGE);
		}
                createMenuVentana();
	}
	
	/**
	*Calcula el MDL de laforma en que lo calcula Remco
	*/
	private void MDLMatric()
	{                
		if((desktop.getSelectedFrame())!=null && (desktop.getSelectedFrame()).getClass().getName().equals("bansy21.Gui.RedFrame"))//
		{
                    RedFrame redF=(RedFrame)desktop.getSelectedFrame();
			if(bPE.casos!=null && redF.redPanel.red.inicio.parents!=null)
			{
				createMonitor("MDL (Remco)", true, bPE.casos.size()+bPE.numVariables);
				MDL mdl=new MDL();
				mdl.red=redF.redPanel.red;
				mdl.casos=bPE.casos;
				mdl.pMonitor=pMonitor;
				mdl.start();
                                this.setSelectedFrame(pMonitor);
				//System.out.println("Resultado:  "+mdl.getMDL(redF.redPanel.red,casos));				
			}
		}
		else
		{
			//enviar un mensaje en el que le diga que debe agregar un red nueva antes     3025.8915996018195
			JOptionPane.showMessageDialog(this,"No ha seleccionado una red. Seleccione la ventana que contiene la red bayesiana que sea evaluar","Error en la selección",JOptionPane.INFORMATION_MESSAGE);
		}
                 createMenuVentana();
	}

	/**
	*Clacula el MDL de la forma en que los calcula nillsson
	*/
	private void MDLNMatric()
	{
		
		if((desktop.getSelectedFrame())!=null && (desktop.getSelectedFrame()).getClass().getName().equals("bansy21.Gui.RedFrame"))//
		{
                    RedFrame redF=(RedFrame)desktop.getSelectedFrame();
			if(bPE.casos!=null && redF.redPanel.red.inicio.parents!=null)
			{			
				createMonitor("MDL (Nils Nilsson)", true, bPE.casos.size()+bPE.numVariables);
				MDL_Nilson mdl=new MDL_Nilson();
				mdl.red=redF.redPanel.red;
				mdl.casos=bPE.casos;
				mdl.pMonitor=pMonitor;
				mdl.start();
                                this.setSelectedFrame(pMonitor);
				//System.out.println("Resultado:  "+mdl.getMDL(redF.redPanel.red,casos));				
			}
		}
		else
		{
			//enviar un mensaje en el que le diga que debe agregar un red nueva antes     3025.8915996018195
			JOptionPane.showMessageDialog(this,"No ha seleccionado una red. Seleccione la ventana que contiene la red bayesiana que sea evaluar","Error en la selección",JOptionPane.INFORMATION_MESSAGE);
		}
                 createMenuVentana();
	}

	

	/**
	*REaliza la clasificacion de ejemplos leidos desde un archivo de ejemplos
	*para una red bayesiana generada con algun algoritmo de la familia de los bayes
	*/
	private void generalClasificacion()
	{
		RedFrame redF=(RedFrame)desktop.getSelectedFrame();
		if(redF!=null)//
		{
			setInitD();

			//leer ejemplos para su clasificacion
			ExampleFileFilter xmlFilter = new ExampleFileFilter("txt", "Text Files");
			chooser.setFileFilter(xmlFilter);
			chooser.setDialogType(JFileChooser.OPEN_DIALOG);
	    int returnVal = chooser.showOpenDialog(this);
	    if(returnVal == JFileChooser.APPROVE_OPTION) 
			{
				String directory = chooser.getSelectedFile().getPath();
				ClasificacionGeneral naiC=new ClasificacionGeneral(redF.redPanel.red);
				Vector tempC=null;
				try
				{
					tempC=(new Archivo2()).leerEjemplos(directory);					
				}catch(Exception e){System.out.println("error clasificacion naive");}
				if (tempC.size()>0)
				{
					System.out.println("la probaba "+naiC.makeClasification(tempC));
				}				
			}
		}
		else
		{
			//enviar un mensaje en el que le diga que debe agregar un red nueva antes     3025.8915996018195
			JOptionPane.showMessageDialog(this,"No ha seleccionado una red","No ha seleccionado una red",JOptionPane.INFORMATION_MESSAGE);
		}
	}
	/**
	*REaliza la clasificacion de ejemplos leidos desde un archivo de ejemplos
	*para una red bayesiana generada con algun algoritmo de la familia de los bayes
	*/
	private void naiveClasification()
	{
		RedFrame redF=(RedFrame)desktop.getSelectedFrame();
		if(redF!=null)//
		{
			setInitD();
			ExampleFileFilter xmlFilter = new ExampleFileFilter("txt", "Text Files");
			chooser.setFileFilter(xmlFilter);
			chooser.setDialogType(JFileChooser.OPEN_DIALOG);
	    int returnVal = chooser.showOpenDialog(this);
	    if(returnVal == JFileChooser.APPROVE_OPTION) 
			{
				String directory = chooser.getSelectedFile().getPath();		    
				ClasificacionNaive naiC=new ClasificacionNaive(redF.redPanel.red);
				Vector tempC=null;
				try
				{
					tempC=(new Archivo2()).leerEjemplos(directory);					
				}catch(Exception e){System.out.println("error clasificacion naive");}
				if (tempC.size()>0)
				{
					System.out.println("la probaba "+naiC.makeClasification(tempC));
				}				
			}
		}
		else
		{
			//enviar un mensaje en el que le diga que debe agregar un red nueva antes     3025.8915996018195
			//System.out.println("No hay ninguna red seleccionada");
			JOptionPane.showMessageDialog(this,"No ha seleccionado una red","No ha seleccionado una red",JOptionPane.INFORMATION_MESSAGE);
		}
	}
	

	private void crossVal()
	{
		DCrossValidation dc=new DCrossValidation(this,"Cross-Validation",true);
		if (dc.aceptar)
		{
			CrossValidation c1=new CrossValidation();			
			//obatener los parametros de bayesN
			double talfa=0;
			double talfaG=0;
			int tprofundidad=0;
			double tminPorcGan=0;

			if (dc.bayesn.isSelected())
			{
				talfaG=(new Double(dc.tAlfa.getText())).doubleValue()/100.00;
				talfa=bPE.alfaG;
				tprofundidad=(new Integer(dc.tProfundidad.getText())).intValue();
				tminPorcGan=(new Double(dc.tIMin.getText())).doubleValue();
			}
			String directory=dc.textFile.getText();
			String baseN=dc.baseName;
			int fold=(new Integer(dc.textFolds.getText())).intValue();
			Archivo tempC=null;
			
			c1.naive=dc.naive.isSelected();
			c1.bayesn=dc.bayesn.isSelected();
			c1.bayes9=dc.bayes9.isSelected();
			c1.guardar=dc.guardar.isSelected();
			if (c1.naive || c1.bayesn || c1.bayes9)
			{			
				try
				{
					tempC=new Archivo();
					bPE.inicio=tempC.leer(directory);
					bPE.casos=tempC.casos;
					bPE.numVariables=tempC.numVariables;
					bPE.varDep=tempC.varDep;
					getValues();
	
					c1.cas=bPE.casos.size();
					c1.alfaG=talfaG;
					c1.alfa=talfa;
					c1.minPorcGan=(double)tminPorcGan;
					c1.profundidad=tprofundidad;
					c1.numVariables=bPE.numVariables;
					c1.baseName=baseN;
					Red red=new Red();
					red.inicio=bPE.inicio;
					red.varDep=bPE.varDep;
					c1.red=red;
					c1.parent=this;
					c1.casos=bPE.casos;				
					createMonitor("Cross-Validation",true,fold);
					c1.pMonitor=pMonitor;
					c1.fold=fold;
					c1.start();
				}
				catch(Exception e){};
			}
			else
			{
				//send a message
				JOptionPane.showMessageDialog(this,"You did not choose any algorithm","Cross-Validation",JOptionPane.INFORMATION_MESSAGE);
			}			
		}
	}
	
	public void holdOut()
	{
		
		DCrossValidation dc=new DCrossValidation(this,"Cross-Validation",false);
		if (dc.aceptar)
		{
			HoldOut c1=new HoldOut();			
			//obatener los parametros de bayesN
			double talfa=0;
			double talfaG=0;
			int tprofundidad=0;
			double tminPorcGan=0;

			if (dc.bayesn.isSelected())
			{
				talfaG=(new Double(dc.tAlfa.getText())).doubleValue()/100.00;
				talfa=bPE.alfaG;
				tprofundidad=(new Integer(dc.tProfundidad.getText())).intValue();
				tminPorcGan=(new Double(dc.tIMin.getText())).doubleValue();
			}

			String directory=dc.textFile.getText();
			String baseN=dc.baseName;
			double hold=(new Double(dc.textFolds.getText())).doubleValue();
			Archivo tempC=null;
			
			c1.naive=dc.naive.isSelected();
			c1.bayesn=dc.bayesn.isSelected();
			c1.bayes9=dc.bayes9.isSelected();
			c1.guardar=dc.guardar.isSelected();
			
			if (c1.naive || c1.bayesn || c1.bayes9)
			{			
				try
				{
					tempC=new Archivo();
					bPE.inicio=tempC.leer(directory);
					bPE.casos=tempC.casos;
					bPE.numVariables=tempC.numVariables;
					bPE.varDep=tempC.varDep;
					getValues();
	
					c1.cas=bPE.casos.size();
					c1.alfaG=talfaG;
					c1.alfa=talfa;
					c1.minPorcGan=(double)tminPorcGan;
					c1.profundidad=tprofundidad;
					c1.numVariables=bPE.numVariables;
					c1.baseName=baseN;
					Red red=new Red();
					red.inicio=bPE.inicio;
					red.varDep=bPE.varDep;
					c1.red=red;
					c1.casos=bPE.casos;
					createMonitor("Hold-Out",true,10);
					c1.parent=this;
					c1.pMonitor=pMonitor;
					c1.hold=hold;
					c1.start();
				}
				catch(Exception e){};
			}
			else
			{
				//send a message
				JOptionPane.showMessageDialog(this,"You did not choose any algorithm","Cross-Validation",JOptionPane.INFORMATION_MESSAGE);
			}			
		}
	}
	
	/**
	*REaliza automaticamante la clasificacion de ejemplos leidos desde un archivo de ejemplos
	*usando una red naive y la inferencia naive
	*/
	private void naiveAndBayesClasification()
	{
		DiaParametros alf=new DiaParametros(this);
		alf.setLocation(200,200);
		alf.show();
		alf.noBayesN=false;			
		if(!alf.cancel)
		{
			
			bPE.alfaG=(new Double(alf.t1.getText())).doubleValue()/100.00;
			bPE.alfa=bPE.alfaG;
			bPE.profundidad=(new Integer(alf.t2.getText())).intValue();
			bPE.minPorcGan=(new Double(alf.t3.getText())).doubleValue();		


			setInitD();
			ExampleFileFilter xmlFilter = new ExampleFileFilter("txt", "Text Files");
			chooser.setFileFilter(xmlFilter);
			chooser.setDialogType(JFileChooser.OPEN_DIALOG);
	    int returnVal = chooser.showOpenDialog(this);
	    if(returnVal == JFileChooser.APPROVE_OPTION) 
			{
				String directory = chooser.getSelectedFile().getPath();
				Archivo tempC=null;
				try
				{
					tempC=new Archivo();
					bPE.inicio=tempC.leer(directory);
					bPE.casos=tempC.casos;
					bPE.numVariables=tempC.numVariables;
					bPE.varDep=tempC.varDep;
					getValues();
					
					Clasificacion c1=new Clasificacion();
					createMonitor("Clasificación",true,100);
					c1.pMonitor=pMonitor;
					c1.cas=bPE.casos.size();
					c1.casos=bPE.casos;
					c1.alfaG=bPE.alfaG;
					c1.alfa=bPE.alfa;
					c1.minPorcGan=(double)bPE.minPorcGan;
					c1.profundidad=bPE.profundidad;
					c1.numVariables=bPE.numVariables;
					c1.inicio=bPE.inicio;
					c1.varDep=bPE.varDep;
					c1.parent=this;
					c1.por=0.8;
					c1.baseName= chooser.getSelectedFile().getName();
					
					c1.start();;
				}catch(Exception e){e.printStackTrace(System.out);}				
					//System.out.println("la probaba "+naiC.makeClasification(tempC));								
			}
		}

			
	/*	}
		else
		{
			//enviar un mensaje en el que le diga que debe agregar un red nueva antes     3025.8915996018195
			System.out.println("No hay ninguna red seleccionada");
		}*/
	}

	/**
	* Leer una red en formato XML(XBN de Microsoft)
	*/
	private void leerRedXMLM()
	{	
		setInitD();
		ExampleFileFilter xmlFilter = new ExampleFileFilter("XML", "XML Extended Marked Languaje Files");
		chooser.setFileFilter(xmlFilter);
		chooser.setDialogType(JFileChooser.OPEN_DIALOG);
    int returnVal = chooser.showOpenDialog(this);
    if(returnVal == JFileChooser.APPROVE_OPTION) 
		{
			String directory = chooser.getSelectedFile().getPath();     
			XMLParser xml=new XMLParser();
			Red red = xml.getRedFromXMLFile(directory);
			agregarRed(red,directory);
		}	
	}


	private void guardarBaseElvM()
	{
		RedFrame redF=(RedFrame)desktop.getSelectedFrame();
		if(redF!=null && bPE.casos!=null)//
		{			
			setInitD();
			ExampleFileFilter xmlFilter = new ExampleFileFilter("elv", "Elvira Format Files");
			chooser.setFileFilter(xmlFilter);
			chooser.setDialogType(JFileChooser.SAVE_DIALOG);
	    int returnVal = chooser.showSaveDialog(this);
	    if(returnVal == JFileChooser.APPROVE_OPTION) 
			{
				String directory = chooser.getSelectedFile().getPath();
				(new Archivo()).saveDataBaseElv(directory,bPE.casos,redF.redPanel.red);
			}
		}
		else
		{
			JOptionPane.showMessageDialog(this,"There is not any selected network","Network",JOptionPane.INFORMATION_MESSAGE);
		}
	}
		
	private void guardarArff()
	{
		RedFrame redF=(RedFrame)desktop.getSelectedFrame();
		if(redF!=null && bPE.casos!=null)//
		{			
			setInitD();
			ExampleFileFilter xmlFilter = new ExampleFileFilter("arff", "arff Format File");
			chooser.setFileFilter(xmlFilter);
			chooser.setDialogType(JFileChooser.SAVE_DIALOG);
	    int returnVal = chooser.showSaveDialog(this);
	    if(returnVal == JFileChooser.APPROVE_OPTION) 
			{
				String directory = chooser.getSelectedFile().getPath();
				(new Archivo()).saveDataBaseArff(directory,bPE.casos,redF.redPanel.red);
			}
		}
		else
		{
			JOptionPane.showMessageDialog(this,"There is not any selected network","Network",JOptionPane.INFORMATION_MESSAGE);
		}
	}

	private void leerArcosElvira()
	{
		if(bPE.inicio!=null)
		{
			setInitD();		
			ExampleFileFilter xmlFilter = new ExampleFileFilter("elv", "Elvira Format Files");
			chooser.setFileFilter(xmlFilter);
			chooser.setDialogType(JFileChooser.OPEN_DIALOG);
			chooser.setDialogTitle("Leer los arcos desde un archivo Elvira");
	    int returnVal = chooser.showOpenDialog(this);
	    if(returnVal == JFileChooser.APPROVE_OPTION) 
			{
				String directory = chooser.getSelectedFile().getPath();
				try
				{
					agregarRed(bPE.inicio,(new Archivo()).leerArcosFromElviraFormat(directory,bPE.inicio),directory);
				}
				catch(Exception e){System.out.println("Error al cargar el archivo "+e.getMessage());};
			}
		}
		else
		{
			JOptionPane.showMessageDialog(this,"You need to load data firts","Data needed",JOptionPane.INFORMATION_MESSAGE);
		}
	}

  // -------------------------------------------------------------------------------------
	/** 	*Crea el progres Monitor 	*/

	private void createMonitor(String algoritmo, boolean determinate, int maxValue)
	{
		pMonitor=new Progress(this,algoritmo,determinate,maxValue,icon);

		// Agregada por AAT
//		 pMonitor.parent = this;

		pMonitor.addInternalFrameListener( new internalFrameListener() );
		pMonitor.addMouseListener( new mouseListener() );
		pMonitor.show();
		desktop.add(pMonitor);

		new Thread(pMonitor).start();
		//pMonitor.setMillisToDecideToPopup(500);
		pMonitor.setProgress(0);
	}
// ------------------------------------------------------------------------
  public boolean HayVentanasAbiertas()
  {
    JInternalFrame[] frames=desktop.getAllFrames();
    if ( frames.length > 0 ) return( true  );
    else                     return( false );
  }
// ------------------------------------------------------------------------
	//este metodo carga los datos desde un archivo de texto
  private void cargarDatos()
  {
     if ( HayVentanasAbiertas() )
     { JOptionPane.showMessageDialog(this,
         "Debe cerrar todas las ventanas antes de cargar nuevos datos",
         "Ventanas", JOptionPane.INFORMATION_MESSAGE);
     }
     else 
     {
	  setInitD();
	  ExampleFileFilter xmlFilter = new ExampleFileFilter("txt", "Text Files (Data Base)");
	  chooser.setFileFilter(xmlFilter);
	  chooser.setDialogTitle("Cargar datos desde una archivo de texto");
	  chooser.setDialogType(JFileChooser.OPEN_DIALOG);
	  int returnVal = chooser.showOpenDialog(this);
	  if(returnVal == JFileChooser.APPROVE_OPTION) 
        {		
          String directory = chooser.getSelectedFile().getPath();
          bPE.numVariables = 6;

          setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
          try
          { 
           bPE.inicio=null;
            bPE.inArco=null;
            Archivo arch=new Archivo();				
            bPE.inicio = arch.leer(directory);
            bPE.casos = arch.casos;				
            bPE.varDep=arch.varDep;
            bPE.varDep2=arch.varDep;
            bPE.numVariables=arch.numVariables;
            getValues();
            Red red =new Red();
            red.inicio=bPE.inicio;
            red.inArco=null;

//            agregarRed(red, directory);
            agregarRed(red, directory, true); //Sin botones


            bPE.baseName=directory;
          } catch(Exception e){};
          
          bPE.Casos = bPE.casos.size();
          setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));		
          probability();
        }
    }
  }
// ------------------------------------------------------------------------
// Del menu Ver.
  void VerParametros()
  {
/*   // JInternalFrame
    VenParametros v1 = new VenParametros( this ); desktop.add( v1 ); v1.toFront();
    try { v1.setSelected(true); } catch (java.beans.PropertyVetoException e) {}
*/
	// JDialog
    VdParametros v1 = new VdParametros( this ); v1.show();
  }
// ------------------------------------------------------------------------

	private void convertir()
	{
		setInitD();
	//	ExampleFileFilter xmlFilter = new ExampleFileFilter("elv", "Elvira Format Files");
	//	chooser.setFileFilter(xmlFilter);
		chooser.setDialogType(JFileChooser.OPEN_DIALOG);
		chooser.setDialogTitle("Lee los arcos de una red DNET y guarda los arcos en formato texto");
	  int returnVal = chooser.showOpenDialog(this);
	  if(returnVal == JFileChooser.APPROVE_OPTION) 
		{
			String directory = chooser.getSelectedFile().getPath();
			try
			{
				Archivo arch=new Archivo();
				arch.leeE(directory,"");
			}
			catch(Exception e){};
		}
	}
// ------------------------------------------------------------------------
/*revisa los datos para obtener los valores posibles de las variables */
	private void getValues()
	{
		int con1=0;
		Node temp=bPE.inicio;
		do
		{
			temp.values=new Vector();
			for(int i=0;i<bPE.casos.size();i++)
			{
                            Object ob= ((Object[])bPE.casos.elementAt(i))[con1];
                            boolean boll=util.miembro(ob,temp.values);
				if(!boll)
				{
					temp.values.addElement(((Object[])bPE.casos.elementAt(i))[con1]);
				}
			}
			if(temp.values.size()==1)
				temp.values.addElement("0");
			//System.out.println(""+temp.values.size());
			temp.table=util.getTable(temp);
			temp=temp.sig;
			con1++;
		}while(temp!=null);
	}
// ------------------------------------------------------------------------
	//**************    guarda los arcos
	private void guardarArcosM()
	{
		RedFrame redF=(RedFrame)desktop.getSelectedFrame();
		if(redF!=null)//
		{
			setInitD();
			ExampleFileFilter xmlFilter = new ExampleFileFilter("txt", "Text Files");
			chooser.setFileFilter(xmlFilter);
			chooser.setDialogType(JFileChooser.SAVE_DIALOG);
			chooser.setDialogTitle("Guarder los arcos de la red");
		  int returnVal = chooser.showSaveDialog(this);
		  if(returnVal == JFileChooser.APPROVE_OPTION) 
			{
				String directory = chooser.getSelectedFile().getPath();
				(new Archivo()).escribirArcos(bPE.inArco,directory);
			}
		}
		else
		{
			JOptionPane.showMessageDialog(this,"There is not any selected network","Network",JOptionPane.INFORMATION_MESSAGE);
		}
	}
	private void leerArcosM()
	{
		if (bPE.inicio!=null)
		{		
			setInitD();
			ExampleFileFilter xmlFilter = new ExampleFileFilter("txt", "Text Files");
			chooser.setFileFilter(xmlFilter);
			chooser.setDialogType(JFileChooser.OPEN_DIALOG);
			chooser.setDialogTitle("Leer arcos");
		  int returnVal = chooser.showOpenDialog(this);
		  if(returnVal == JFileChooser.APPROVE_OPTION) 
			{
				String directory = chooser.getSelectedFile().getPath();
				try
				{
				  bPE.inArco=(new Archivo()).leerArcos(directory, bPE.inicio);
					agregarRed(bPE.inicio, bPE.inArco, chooser.getSelectedFile().getName());
				}
				catch(Exception e){System.out.println("Error al Leer el archivo "+e.getMessage());};			
			}
			createMenuVentana();
		}
		else
		{
			JOptionPane.showMessageDialog(this,"You need to load data firts","Data needed",JOptionPane.INFORMATION_MESSAGE);
		}

	}
// --------------------------------------------------------------------------------
//	private void  saveRedImage()
	public void  saveRedImage()
	{		 
		RedFrame redF=(RedFrame)desktop.getSelectedFrame();
		if(redF!=null)
		{
			setInitD();
			ExampleFileFilter xmlFilter = new ExampleFileFilter("gif", "Image Files");
			chooser.setFileFilter(xmlFilter);
			chooser.setDialogType(JFileChooser.SAVE_DIALOG);
			chooser.setDialogTitle("Guarder imagen de la red (.gif)");
			int returnVal = chooser.showSaveDialog(this);
			if(returnVal == JFileChooser.APPROVE_OPTION) 
			{
				String directory = chooser.getSelectedFile().getPath();
				Image ima=null;
//				ima=redF.redPanel.createImage(redF.redPanel.getWidth(),redF.redPanel.getHeight());
				ima=redF.redPanel.createImage( 640,435 );

				redF.redPanel.paint(ima.getGraphics());
				int index=bPE.baseName.indexOf(".");
				//(new Archivo()). guardarGif(ima,"pruebas/"+alfaG+"_"+profundidad+"_"+minPorcGan+"_"+baseName.substring(0,index)+".gif");
				(new Archivo()). guardarGif(ima,directory);
			}			
		}
		else
		{	 
		 //enviar mensaje diciendo que no hay una red
		 JOptionPane.showMessageDialog(this,"There is not any selected network","Network",JOptionPane.INFORMATION_MESSAGE);
		}
	}
	
// -------------------------------------------------------------------------------------
	//*****************   agrega internal frames******************
		//agrega un Internal frame en el que se digbuijara la red
	public void agregarRed(Node inic, Arco inicA,String nombre)
	{
//		RedFrame redFrame=new RedFrame(nombre);
		RedFrame redFrame=new RedFrame(nombre, this);
		Red red=new Red();

		red.inicio=inic;
		red.inArco=inicA;
		red.varDep=bPE.varDep;
		redFrame.redPanel.red=red;
		redFrame.redPanel.numVariables=bPE.numVariables;
		redFrame.redPanel.parent=this;
		redFrame.addInternalFrameListener(new internalFrameListener());
		redFrame.setIcon(icon);
		redFrame.addMouseListener(new mouseListener());
		redFrame.show();
		desktop.add(redFrame);
		try
		{
			redFrame.setMaximum(true);
		}catch(Exception e){};
		try 
		{
			redFrame.setSelected(true);
		} catch (java.beans.PropertyVetoException e) {}
		createMenuVentana();
	}
// -------------------------------------------------------------------------------------
	//agrega un Internal frame en el que se digbuijara la red
	public void agregarRed(String nombre)
	{
//		RedFrame redFrame=new RedFrame(nombre);
		RedFrame redFrame=new RedFrame(nombre, this);
		Red red=new Red();
		redFrame.redPanel.red=red;
		redFrame.redPanel.numVariables=bPE.numVariables;
		redFrame.redPanel.firstPaint=false;
		redFrame.redPanel.parent=this;
		redFrame.addInternalFrameListener(new internalFrameListener());
		redFrame.addMouseListener(new mouseListener());
		redFrame.setIcon(icon);
		redFrame.show();
		desktop.add(redFrame);
		try
		{
			redFrame.setMaximum(true);
		}catch(Exception e){};
		try 
		{
			redFrame.setSelected(true);
		} catch (java.beans.PropertyVetoException e) {}
		createMenuVentana();
	}

// -------------------------------------------------------------------------------------
	//agrega un Internal frame en el que se digbuijara la red
	public void agregarRed(Red red, String nombre)
	{
//		RedFrame redFrame=new RedFrame(nombre);
		RedFrame redFrame=new RedFrame(nombre, this);
		redFrame.redPanel.red=red;
		redFrame.redPanel.numVariables=bPE.numVariables;
		redFrame.redPanel.parent=this;
		redFrame.addInternalFrameListener(new internalFrameListener());
		redFrame.addMouseListener(new mouseListener());
		redFrame.setIcon(icon);
		redFrame.show();
		desktop.add(redFrame);
		try
		{
                    redFrame.setMaximum(true);
		}catch(Exception e){};
		try 
		{
			redFrame.setSelected(true);
		} catch (java.beans.PropertyVetoException e) {}
		createMenuVentana();
	}
// -------------------------------------------------------------------------------------
	//agrega un Internal frame en el que se digbuijara la red
	public void agregarRed(Red red, String nombre, boolean ConBotones)
	{
//		RedFrame redFrame=new RedFrame(nombre, ConBotones);
		RedFrame redFrame=new RedFrame(nombre, ConBotones, this);
		redFrame.redPanel.red=red;
		redFrame.redPanel.numVariables=bPE.numVariables;
		redFrame.redPanel.parent=this;		
		redFrame.addInternalFrameListener(new internalFrameListener());
		redFrame.addMouseListener(new mouseListener());
		redFrame.setIcon(icon);
		redFrame.show();
		desktop.add(redFrame);
		try
		{
			redFrame.setMaximum(true);
		}catch(Exception e){};
		try 
		{
			redFrame.setSelected(true);
		} catch (java.beans.PropertyVetoException e) {}
		createMenuVentana();
	}
        
        public void setSelectedFrame(Progress pmonitor)
        {
            try 
		{
			pmonitor.setSelected(true);
                        System.out.println("selccion");
		} catch (java.beans.PropertyVetoException e) {}
		createMenuVentana();
        }

	//**************    Esta clase la usa el internalFrame 
	public class mouseListener implements MouseListener
	{
		public void mouseClicked(MouseEvent e)
		{			 
		}
		public void mousePressed(MouseEvent e)
		{
			 //System.out.println("Frame press");			 
		}
		public void mouseReleased(MouseEvent e)
		{
		}

		public void mouseEntered(MouseEvent e)
		{
/*
			 RedFrame  rd= (RedFrame)desktop.getSelectedFrame();
			 if(rd!=null) { inArco=rd.redPanel.red.inArco;  }
*/

// Agregada por AAT
			JInternalFrame rd2 = desktop.getSelectedFrame();
			if( rd2 != null )
			{
			  try{ 
				RedFrame rd = (RedFrame)desktop.getSelectedFrame();
				bPE.inArco=rd.redPanel.red.inArco;       
			  }catch(Exception ex){};
			}
		}

		public void mouseExited(MouseEvent e)
		{        
	        //System.out.println("Frame salio");           
		}
	}

// -------------------------------------------------------------------------------------
	//  *************    Clase internalFrameListener
	public class internalFrameListener implements InternalFrameListener
	{
		public void internalFrameActivated(InternalFrameEvent e)
		{
			//
			//System.out.println("Activada");
		}
		public void internalFrameOpened(InternalFrameEvent e)
		{
		}
		public void internalFrameClosing(InternalFrameEvent e){}
		public void internalFrameClosed(InternalFrameEvent e)
		{
                  
		  createMenuVentana();
		}
		public void internalFrameIconified(InternalFrameEvent e)
		{
				//System.out.println("Iconified");
		}
		public void internalFrameDeiconified(InternalFrameEvent e)
		{
				//System.out.println("Deiconified");
		}
		public void internalFrameDeactivated(InternalFrameEvent e)
		{
				//System.out.println("Deactivated");
		}
	}

// -------------------------------------------------------------------------------------
	/********************ALGORITMOS*************************/
	private void bayes()
	{	
		if (bPE.inicio!=null)
		{		
			DiaParametros alf=new DiaParametros(this);
		//	alf.setLocation(200,200);
			alf.l1.setText("Alfa:(%)");
			alf.l2.setEnabled(false);
			alf.t2.setEnabled(false);
			alf.l3.setEnabled(false);
			alf.t3.setEnabled(false);
			alf.show();
			
			if(!alf.cancel)
			{
				setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
				bPE.alfaG=(new Double(alf.t1.getText())).doubleValue()/100.00;
				bPE.alfa=bPE.alfaG;
				Bayes b=new Bayes();		
				b.casos=bPE.casos.size();
				b.alfa=bPE.alfa;
				b.pro.casos=bPE.casos;		 
				RedFrame redF=(RedFrame)desktop.getSelectedFrame();
				Calendar date1=Calendar.getInstance();
  
				createMonitor("Bayes2",true,bPE.numVariables);
				b.pMonitor=pMonitor;
				b.inicio=bPE.inicio;
				b.parent=this;
				b.baseName=bPE.baseName;
						
					
				if(redF!=null)
				{	
					if(redF.redPanel.selectedN!=null)
					{
						b.varDepName=redF.redPanel.selectedN.name;
						b.pro.varDep=redF.redPanel.selectedN;						
					}
					else
					{
						b.varDepName=bPE.varDep.name;
						b.pro.varDep=bPE.varDep;
					}				
					b.start();							
				}
				else if(bPE.inicio != null)
				{
					b.varDepName=bPE.varDep.name;
					b.pro.varDep=bPE.varDep;
					b.start();				
				}
				Calendar date2=Calendar.getInstance();													
				System.out.println(""+util.tiempoEmpleado(date1,date2));
				setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
			}
		}
		else
		{
			JOptionPane.showMessageDialog(this,"Necesita cargar los datos","Datos",JOptionPane.INFORMATION_MESSAGE);
		}
	}
// --------------------------------------------------------------------------
	private void bayes2()
	{
		if (bPE.inicio!=null)
		{
			DiaParametros alf=new DiaParametros(this);
			//alf.setLocation(200,200);
			alf.l1.setText("Alfa:(%)");
			alf.l2.setEnabled(false);
			alf.t2.setEnabled(false);
			alf.l3.setEnabled(false);
			alf.t3.setEnabled(false);
			alf.show();
			
			if(!alf.cancel)
			{
				setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
				bPE.alfaG=(new Double(alf.t1.getText())).doubleValue()/100.00;
				bPE.alfa=bPE.alfaG;
				Bayes2 b2=new Bayes2();
				b2.casos=bPE.casos.size();
				b2.alfa=bPE.alfa;
				b2.pro.casos=bPE.casos;
			  
				b2.varDepName=bPE.varDep.name;
				b2.pro.varDep=bPE.varDep;
  
				
				
				RedFrame redF=(RedFrame)desktop.getSelectedFrame();
				Calendar date1=Calendar.getInstance();					
				if(redF!=null)
				{
					if(redF.redPanel.selectedN!=null)
					{
						b2.varDepName=redF.redPanel.selectedN.name;
						b2.pro.varDep=redF.redPanel.selectedN;						
					}
					else
					{
						b2.varDepName=bPE.varDep.name;
						b2.pro.varDep=bPE.varDep;
					}
					if(redF.redPanel.red.inArco==null)
					{
						redF.redPanel.red=b2.bayes2(bPE.inicio);
						redF.redPanel.repaint();
						redF.setTitle(bPE.baseName+"_Bayes2");
					}
					else
					{
						agregarRed(b2.bayes2(bPE.inicio),bPE.baseName+"_Bayes2");
					}
				}
				else if(bPE.inicio!=null)
				{				
					agregarRed(b2.bayes2(bPE.inicio),bPE.baseName+"_Bayes2");
				}
				Calendar date2=Calendar.getInstance();													
				System.out.println(""+util.tiempoEmpleado(date1,date2));
				setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
			}
		}
		else
		{
			JOptionPane.showMessageDialog(this,"Necesita cargar los datos","Datos",JOptionPane.INFORMATION_MESSAGE);
		}
	}
// --------------------------------------------------------------------------
	private void bayes5()
	{
		if (bPE.inicio!=null)
		{		
			DiaParametros alf=new DiaParametros(this);
			//alf.setLocation(200,200);
			alf.l1.setText("Alfa:(%)");
			alf.l2.setEnabled(false);
			alf.t2.setEnabled(false);
			alf.l3.setEnabled(false);
			alf.t3.setEnabled(false);
			alf.show();
			
			if(!alf.cancel)
			{
				setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
				bPE.alfaG=(new Double(alf.t1.getText())).doubleValue()/100.00;
				bPE.alfa=bPE.alfaG;
	  
				Bayes5 b5=new Bayes5();
				b5.casos=bPE.casos.size();
				b5.alfa=bPE.alfa;
				b5.pro.casos=bPE.casos;
			  //if(selectedN==null)
				//{
					b5.varDepName=bPE.varDep.name;
					b5.pro.varDep=bPE.varDep;
				//}
				//else
				//{
					//b2.varDepName=selectedN.name;
				//}
				RedFrame redF=(RedFrame)desktop.getSelectedFrame();
				Calendar date1=Calendar.getInstance();
				createMonitor("Bayes-N",true,bPE.numVariables);
				b5.pMonitor=pMonitor;			
				b5.inicio=bPE.inicio;
				b5.parent=this;
				b5.baseName=bPE.baseName;
				if(redF!=null)
				{
					if(redF.redPanel.selectedN!=null)
					{
						b5.varDepName=redF.redPanel.selectedN.name;
						b5.pro.varDep=redF.redPanel.selectedN;						
					}
					else
					{
						b5.varDepName=bPE.varDep.name;
						b5.pro.varDep=bPE.varDep;
					}
					b5.start();
					/*
					if(redF.redPanel.red.inArco==null)
					{
						redF.redPanel.red=b5.bayes5(inicio);
						redF.redPanel.repaint();
						redF.setTitle(baseName+"_Bayes5");
					}
					else
					{
						agregarRed(b5.bayes5(inicio),baseName+"_Bayes5");
					}
							*/
				}
				else if(bPE.inicio!=null)
				{			
					//agregarRed(b5.bayes5(inicio),baseName+"_Bayes5");
					b5.start();
				}	
				Calendar date2=Calendar.getInstance();													
				System.out.println(""+util.tiempoEmpleado(date1,date2));
				setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
			}
		}
		else
		{
			JOptionPane.showMessageDialog(this,"Necesita cargar los datos","Datos",JOptionPane.INFORMATION_MESSAGE);
		}
	}	
// --------------------------------------------------------------------------
	private void bayesN()
	{
		if (bPE.inicio!=null)
		{		
			DiaParametros alf=new DiaParametros(this);
			//alf.setLocation(200,200);
			alf.setVisible(true);
			alf.noBayesN=false;			
			if(!alf.cancel)
			{
				setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
				bPE.alfaG=(new Double(alf.t1.getText())).doubleValue()/100.00;
				bPE.alfa=bPE.alfaG;

				bPE.profundidad=(new Integer(alf.t2.getText())).intValue();
				bPE.minPorcGan=(new Double(alf.t3.getText())).doubleValue();
				BayesN bN=new BayesN();
				bN.casos=bPE.casos.size();
				bN.alfaG=bPE.alfaG;
				bN.alfa=bPE.alfa;
				bN.minPorcGan=(double)bPE.minPorcGan;
				bN.profundidad=bPE.profundidad;
				bN.numVariables=bPE.numVariables;
				bN.pro.casos=bPE.casos;
				bN.baseName=bPE.baseName;		
				
				bN.varDepName=bPE.varDep.name;
				bN.pro.varDep=bPE.varDep;
  
				createMonitor("Bayes-N",true,bPE.numVariables);
				bN.pMonitor=pMonitor;			
				bN.inicio=bPE.inicio;
				bN.parent=this;
				bN.baseName=bPE.baseName;
				
				RedFrame redF=(RedFrame)desktop.getSelectedFrame();
				
				if(redF!=null)
				{
					if(redF.redPanel.selectedN!=null)
					{
						bN.varDepName=redF.redPanel.selectedN.name;
						bN.pro.varDep=redF.redPanel.selectedN;						
					}
					else
					{
						bN.varDepName=bPE.varDep.name;
						bN.pro.varDep=bPE.varDep;
					}
					bN.start();
				}
				else if(bPE.inicio!=null)
				{
					bN.start();				
				}			
                               // positionBySOM pos=new positionBySOM(redF.redPanel.red);
                                //pos.calcPositionBySOM();
				setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                                
			}
		}
		else
		{
			JOptionPane.showMessageDialog(this,"Necesita cargar los datos","Datos",JOptionPane.INFORMATION_MESSAGE);
		}
            createMenuVentana();
	}
// --------------------------------------------------------------------------
	private void bayesNn()
	{
		if (bPE.inicio!=null)
		{		
			DiaParametros alf=new DiaParametros(this);
			//alf.setLocation(200,200);
			alf.show();
			alf.noBayesN=false;			
			if(!alf.cancel)
			{
				setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
				bPE.alfaG=(new Double(alf.t1.getText())).doubleValue()/100.00;
				bPE.alfa=bPE.alfaG;
				bPE.profundidad=(new Integer(alf.t2.getText())).intValue();
				bPE.minPorcGan=(new Double(alf.t3.getText())).doubleValue();
				BayesNn bN=new BayesNn();
				bN.casos=bPE.casos.size();
				bN.alfaG=bPE.alfaG;
				bN.alfa=bPE.alfa;
				bN.minPorcGan=(double)bPE.minPorcGan;
				bN.profundidad=bPE.profundidad;
				bN.numVariables=bPE.numVariables;
				bN.pro.casos=bPE.casos;
			  
				bN.varDepName=bPE.varDep.name;
				bN.pro.varDep=bPE.varDep;
				
	
				RedFrame redF=(RedFrame)desktop.getSelectedFrame();
				Calendar date1=Calendar.getInstance();
				if(redF!=null)
				{
					if(redF.redPanel.selectedN!=null)
					{
						bN.varDepName=redF.redPanel.selectedN.name;
						bN.pro.varDep=redF.redPanel.selectedN;						
					}
					else
					{
						bN.varDepName=bPE.varDep.name;
						bN.pro.varDep=bPE.varDep;
					}
					if(redF.redPanel.red.inArco==null)
					{
						redF.redPanel.red=bN.bayesN(bPE.inicio);
						redF.redPanel.repaint();
						redF.setTitle(bPE.baseName+"_BayesNn");
					}
					else
					{
						agregarRed(bN.bayesN(bPE.inicio),bPE.baseName+"_BayesNn");
					}				
				}
				else if(bPE.inicio!=null)
				{
					agregarRed(bN.bayesN(bPE.inicio),bPE.baseName+"_BayesNn");
				}
				Calendar date2=Calendar.getInstance();													
				System.out.println(""+util.tiempoEmpleado(date1,date2));
				setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
			}
		}
		else
		{
			JOptionPane.showMessageDialog(this,"Necesita cargar los datos","Datos",JOptionPane.INFORMATION_MESSAGE);
		}
	}
// --------------------------------------------------------------------------
		/**
	* Obtiene la red Bayes9
	*/
	private void bayes9()
	{
        if(bPE.inicio!=null)
        {		
          Bayes9 b=new Bayes9();
          b.inicio=bPE.inicio;
          createMonitor("Bayes-9",false,bPE.numVariables);
          b.pMonitor=pMonitor;
          b.pro.casos=bPE.casos;
          b.parent=this;		
          b.varDepName=bPE.varDep.name;			
          File f=new File(bPE.baseName);
          b.baseName=f.getName();
          b.start();
        }
        else
          JOptionPane.showMessageDialog(this,"Necesita cargar los datos","Datos",JOptionPane.INFORMATION_MESSAGE);
	}
// --------------------------------------------------------------------------
        
        private void MP()
	{
		if (bPE.inicio!=null)
		{		
			
				setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
				
				MP_Bayes MP=new MP_Bayes();
				MP.casos=bPE.casos.size();
				
				MP.alfa=bPE.alfa;
				
				MP.pro.casos=bPE.casos;
				MP.baseName=bPE.baseName;		
				
				MP.varDepName=bPE.varDep.name;
				MP.pro.varDep=bPE.varDep;
  
				createMonitor("MP Bayes",true,bPE.numVariables);
				MP.pMonitor=pMonitor;			
				MP.inicio=bPE.inicio;
				MP.parent=this;
				MP.baseName=bPE.baseName;
				
				RedFrame redF=(RedFrame)desktop.getSelectedFrame();
				
				if(redF!=null)
				{
					if(redF.redPanel.selectedN!=null)
					{
						MP.varDepName=redF.redPanel.selectedN.name;
						MP.pro.varDep=redF.redPanel.selectedN;						
					}
					else
					{
						MP.varDepName=bPE.varDep.name;
						MP.pro.varDep=bPE.varDep;
					}
					MP.start();
				}
				else if(bPE.inicio!=null)
				{
					MP.start();				
				}			
                                //positionBySOM pos=new positionBySOM(redF.redPanel.red);
                                //pos.calcPositionBySOM();
				setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                                
		
		}
		else
		{
			JOptionPane.showMessageDialog(this,"Necesita cargar los datos","Datos",JOptionPane.INFORMATION_MESSAGE);
		}
            createMenuVentana();
	}
//----------------------------------------------------------------------------
	/**
	* Obtiene la red NaiveBayes
	*/
	private void naiveBayes()
	{
        if(bPE.inicio!=null)
        {
          Red red;
          NaiveBayes nai=new NaiveBayes();
          RedFrame redF=(RedFrame)desktop.getSelectedFrame();
          if(redF!=null)
            if(redF.redPanel.selectedN!=null) nai.varDep=redF.redPanel.selectedN;
            else nai.varDep=bPE.varDep;
          else nai.varDep=bPE.varDep;
          nai.pro.casos=bPE.casos;
          red=nai.getRedNaive(bPE.inicio);
          agregarRed(red,bPE.baseName+"_NaiveBayes");
        }
        else
          JOptionPane.showMessageDialog(this,"Necesita cargar los datos","Datos",JOptionPane.INFORMATION_MESSAGE);
	}
// --------------------------------------------------------------------------
	private void naiveInferenceM()
	{
        RedFrame redF=(RedFrame)desktop.getSelectedFrame();
        if(redF!=null)
        {  NaiveInference nai=new NaiveInference();
           if(redF.redPanel.selectedN!=null) nai.varDep=redF.redPanel.selectedN;
           else nai.varDep=bPE.varDep;
           System.out.println(""+nai.getProbability(redF.redPanel.red));
        }
        else
          JOptionPane.showMessageDialog(this,"Seleccione una red.","Red",JOptionPane.INFORMATION_MESSAGE);
	}
        
        // --------------------------------------------------------------------------	
// Métodos para Organizar Ventanas
// --------------------------------------------------------------------------	
	public void VenOrgMenuCascada()
      { int ancho, alto, delta=30;
        JInternalFrame f;
        JInternalFrame[] aframe = desktop.getAllFrames();
        ancho = (int)desktop.getWidth()  - delta * (aframe.length - 1);
        alto  = (int)desktop.getHeight() - delta * (aframe.length - 1);
        for(int k=0; k < aframe.length; k++)
        { f = aframe[k]; 
          try{ f.setIcon( false ); }
          catch( java.beans.PropertyVetoException e ) {};
          try{ f.setMaximum( false ); }
          catch( java.beans.PropertyVetoException e ) {}; 
          f.setSize( ancho, alto ); f.setLocation( k * delta, k * delta );   
        }
      }
// --------------------------------------------------------------------------	
	public void VenOrgMenuRejilla()
      {
        int ancho, alto, Nren, k=0;
        JInternalFrame f;
        JInternalFrame[] aframe = desktop.getAllFrames();
        Nren = (int)aframe.length / 2;
        if ( aframe.length % 2 == 1 ) Nren++; //Num d Ventanas impares
        ancho = (int)desktop.getWidth() / 2;
        alto  = (int)desktop.getHeight() / Nren;
        for(int r=0; r<Nren; r++)
          for(int c=0; (c < 2) && (k < aframe.length) ; c++)
          { f = aframe[k]; k++;
            try{ f.setIcon( false ); }
            catch( java.beans.PropertyVetoException e ) {};
            try{ f.setMaximum( false ); }
            catch( java.beans.PropertyVetoException e ) {}; 
            f.setSize( ancho, alto );
            if (c == 0 ) f.setLocation( 0, r * alto );   // Col izquierda
            else         f.setLocation( ancho, r * alto ); // Col derecha            
          }
      }
// --------------------------------------------------------------------------	
	public void VenOrgMenuMosaicoHorizontal()
      { int ancho;
        JInternalFrame f;
        JInternalFrame[] aframe = desktop.getAllFrames();
        ancho = desktop.getWidth() / aframe.length;
        for(int k=0; k < aframe.length; k++ )
        { f = aframe[k];
          try{ f.setIcon( false ); }
          catch( java.beans.PropertyVetoException e ) {};
          try{ f.setMaximum( false ); }
          catch( java.beans.PropertyVetoException e ) {}; 
          f.setSize( ancho, desktop.getHeight() ); f.setLocation( k * ancho, 0);
        }
      }
// --------------------------------------------------------------------------	
	public void VenOrgMenuMosaicoVertical()
      { int alto;
        JInternalFrame f;
        JInternalFrame[] aframe = desktop.getAllFrames();
        alto = desktop.getHeight() / aframe.length;
        for(int k=0; k < aframe.length; k++ )
        { f = aframe[k];
          try{ f.setIcon( false ); }
          catch( java.beans.PropertyVetoException e ) {};
          try{ f.setMaximum( false ); }
          catch( java.beans.PropertyVetoException e ) {}; 
          f.setSize( desktop.getWidth() , alto ); f.setLocation( 0, k * alto );
        }
      }
// --------------------------------------------------------------------------	
	public void VenOrgMenuMinimizar()
      { JInternalFrame f;
        JInternalFrame[] aframe = desktop.getAllFrames();
        for(int k=0; k < aframe.length; k++ )
        { f = aframe[k];
          try{ f.setIcon( true ); }
          catch( java.beans.PropertyVetoException e ) {};
        }
      }
// --------------------------------------------------------------------------	
	public void VenOrgMenuRestaurar()
      { JInternalFrame f;
        JInternalFrame[] aframe = desktop.getAllFrames();
        for(int k=0; k < aframe.length; k++ )
        { f = aframe[k];
          try{ f.setIcon( false ); }
          catch( java.beans.PropertyVetoException e ) {};
          try{ f.setMaximum( false ); }
          catch( java.beans.PropertyVetoException e ) {};         
        }
      }
// --------------------------------------------------------------------------	
	public void VenOrgMenuMaximizar()
      { JInternalFrame f;
        JInternalFrame[] aframe = desktop.getAllFrames();
        for(int k=0; k < aframe.length; k++ )
        { f = aframe[k];
          try{ f.setMaximum( true ); }
          catch( java.beans.PropertyVetoException e ) {};
        }
      }
// --------------------------------------------------------------------------	
    // esta clase es la encargada de recivir los eventos del menu y de la barra de hts
	public class EventHelper implements ActionListener
	{
        public void actionPerformed(java.awt.event.ActionEvent event)
        {
           Object objeto=event.getSource();
           for ( int i=0; i < jmVentana.getItemCount(); i++ )
             if( objeto == jmVentana.getItem(i) )
               try{ 
                 ((JMenuItemExtended)jmVentana.getItem(i)).InternalFrame.setSelected(true); 
                 break;
               }catch(Exception e){ System.out.println("Error Cast, Menu ventana"); };
               
     // --------------------------------------

        }
	}       
       
        private void guardarProyecto()
        {
            setInitD();	
           // ExampleFileFilter xmlFilter = new ExampleFileFilter("BNproy", "Proyecto Bansy 2");			
            //chooser.setFileFilter(xmlFilter);
            chooser.setDialogType(JFileChooser.SAVE_DIALOG);
            chooser.setDialogTitle("Guarder los arcos de la red");
            int returnVal = chooser.showSaveDialog(this);
            addPanelsAndMonitorsProperties();
            if(returnVal == JFileChooser.APPROVE_OPTION)
            {	
                String directory = chooser.getSelectedFile().getPath();		
                (new Archivo2()).guardarProyecto(bPE,directory);
            }
        }
        
        private void addPanelsAndMonitorsProperties()
        {
           Object[] frames=(Object[])desktop.getAllFrames();
           bPE.netsOfPanels=new Red[frames.length];
           bPE.namesPanels=new String[frames.length];
           for (int i=0;i<frames.length;i++)
           {
               String clase=frames[i].getClass().toString();
              System.out.print(clase);
               
           }
        }
        
        private void abrirProyecto()
        {
        
        }
        
        
       
    
}
